### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by buildersbrewery** [facelessuser/ColorHelper#100]
## Description

Error on startup

```text
ColorHelper: 
Traceback (most recent call last):
  File "color_helper in ..\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 1334, in payload
  File "color_helper in ..\sublime3\Data\Installed Packages\ColorHelper.sublime-package", line 1070, in do_search
TypeError: int() argument must be a string or a number, not 'NoneType'
```

## Support Info

- Sublime Text Build 3156
- Windows 10 Pro x64 Version 1709
- ColorHelper: `v2.5.1`
- mdpopups: `v3.2.0`
- markdown: `v2.6.9`
- pygments: `v2.1a0`
- jinja2: `v2.8`

## Steps to Reproduce Issue

Started Sublime with `"hot_exit": false`.

**Comment by facelessuser** [comment]
This is a common Sublime bug that is run into from time to time.  We are actually protecting against no value being found:

```py
old_box_height = int(settings.get('color_helper.box_height', 0))
```
It should give us a `0` if there is no `color_helper.box_height`, but some times settings aren't initialized (I'm only guessing at this), and then we get None for some reason.  This is really a Sublime issue.  What's interesting is these types of bugs aren't always reproducible across different machines.

I can try and quit the operation if that value turns up `None`, but you will also find later that some other setting I try to access will turn up `None`.  A bug report should really be filed on Sublime (if one is not currently).  It is getting to a point where I might have to write my own setting wrapper just so I can force a sane default in this scenario.

**Comment by facelessuser** [comment]
Closing this issue as it is stale and I've yet to reliably reproduce such an issue.

If this is an issue we start running into a lot again in the future, we can open a new issue and look into it again.

@gir-bot add invalid

**Comment by facelessuser** [comment]
@gir-bot add S: invalid
