### ISSUE TITLE
Some color codes are not marked.

### ISSUE THREAD

**Issue by emkei-cz** [facelessuser/ColorHelper#102]
- ST ver.: 3143
- Platform: linux
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.0
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

Hi,
Can you please advise me how to edit the syntax.
Make all color codes marked?
https://s18.postimg.org/agiyakm7d/image.png

I don't know exactly how to edit this code:
https://pastebin.com/raw/bTC8dxNw

**Comment by facelessuser** [comment]
I'm not familiar with the notation you are using.  You will have to analyze the scopes for the color portion of that syntax and make a pull request including those scopes in the scanning.
