### ISSUE TITLE
Fails to insert text while a selection is active

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ColorHelper#104]
## Description

When selecting **Color Helper: Show Color Picker** from the command palette while having a non-empty selection in the view, no color/text will be inserted by clicking on `>>>` links.

No errors on console.

## Support Info

- ST ver.: 3156
- Platform: linux
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.2.0
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Select some text
2. Run **Color Helper: Show Color Picker**
3. Try to insert any color by clicking on a `>>>` link

The popup will close and nothing will be inserted.

**Comment by facelessuser** [comment]
Finally getting around to looking at this. I believe originally it was restricted to no selection as we have logic to look adjacent to the cursor and see if we are replacing an existing color. If so, we delete it. But I guess if something is already selected, we could just ignore that logic and replace whatever is selected.
