### ISSUE TITLE
inline_previews doesn't work on .scss files (but on .css)

### ISSUE THREAD

**Issue by christophlieck** [facelessuser/ColorHelper#107]
I don't get inline color previews in .scss files, but in css files (compiled from the same source). All other features such as Color Info Panel do work (see screenshot from .scss attached).

- ST 3.0, Build 3143
- Syntax Highlighter is [SASS](https://packagecontrol.io/packages/Sass)
- Theme: [Material Theme](https://packagecontrol.io/packages/Material%20Theme) with color scheme "Material Dark"
- [Sublime linter](https://packagecontrol.io/packages/SublimeLinter) with [SCSS lint](https://packagecontrol.io/packages/SublimeLinter-contrib-scss-lint) installed but disabled
- settings:  "inline_previews": true
- no console errors or warnings etc.

## Support Info

- ST ver.: 3143
- Platform: osx
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. open .scss file
2. n. a.
3. n. a.
![bildschirmfoto 2018-02-07 um 21 25 20](https://user-images.githubusercontent.com/3341183/35940555-dfa722de-0c4f-11e8-927d-734de1d62f24.JPG)

**Comment by sajmonella9** [comment]
And on Naomi Syntax (Naomi Language Package Support). Can someone release that fix ? will be great. Thx.

**Comment by certainlyakey** [comment]
The same problem for Sublime Text 3.1.1, inline color previews not appearing (no console errors) in SCSS files on macOS High Sierra (with https://github.com/P233/Syntax-highlighting-for-Sass package for handling those). What's pretty interesting is that it worked with the same setup (I sync the Sublime Text config via Dropbox) on El Capitan.

**Comment by mintymatt** [comment]
Has any progress been made on this issue?

**Comment by oleonard** [comment]
I'm having the same issue. Windows 10, Sublime Text 3.1.1, build 3176. Color previews work with .css but not .scss.

**Comment by hahamimidido** [comment]
same here , macOS 10.14 Mojave Sublime Text 3176, inline preview not working.

**Comment by dportalesr** [comment]
I solved it by making sure the `scan_scopes` setting contains the actual scope in my scss file.

In my case, my scss file was reporting this scope (use [StatusMessage](https://packagecontrol.io/packages/StatusMessage) or [ScopeAlways](https://packagecontrol.io/packages/ScopeAlways)):
![image](https://user-images.githubusercontent.com/34167503/49693787-6d011180-fb42-11e8-8558-4edbc9e9f23d.png)

Whereas my settings file, had these in the `scan_scopes` array (under the `source.scss` group):
![image](https://user-images.githubusercontent.com/34167503/49693798-a6d21800-fb42-11e8-8823-063414540b31.png)

So I simply added it there:
![image](https://user-images.githubusercontent.com/34167503/49693816-f7497580-fb42-11e8-8975-297a25f0f830.png)

I've been using this for some time and it suddenly stopped working. I suspect some recent syntax highlighter may have changed the scope reported from my scss files. Fortunately, I can customize it.

**Comment by katerlouis** [comment]
Is there a reason this hasn't been pulled and released yet?

**Comment by facelessuser** [comment]
Priority and free time. I support a lot of projects. The priority of ColorHelper at times is a bit lower than other projects simply because on a day to day basis, it doesn't get used by me as much as others as I'm not a web developer.

I'm hoping to get a couple things in sometime soon, but we'll see.

**Comment by facelessuser** [comment]
To make it more manageable, each supported SCSS and Sass syntax package was broken up into separate rules. I went through and did a basic test of all those packages that were commented in the settings file. Any packages outside the commented packages are not currently supported. 

If any additional issues are found, a new issue should be opened. This should make it easier to patch specific SCSS and Sass packages.
