### ISSUE TITLE
ColorHelper stopped working

### ISSUE THREAD

**Issue by Draghmar** [facelessuser/ColorHelper#108]
## Description
Suddenly plugin has stopped working. Previews are gone and I can't invoke the popup. I didn't change anything to ColorHelper lately and I didn't install anything new so I have no idea where the issue could came from. It's like there was no ColorHelper at all. I tried disabling/enabling and reinstalling.
I see now that there are two entries in the Support Info that are weird to say at least. But I don't know if that is something new or if it was there for some time. So I don't if it's related in any way.
## Support Info

- ST ver.: 3156
- Platform: windows
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- markdown ver.: Version could not be acquired!
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

My settings:
```json
{
	"use_webcolor_names": false,
	"graphic_size": "large",
	"use_hex_color_picker": false
}
```

## Steps to Reproduce Issue
1. Just open any css file that has color declarations.

**Comment by facelessuser** [comment]
It looks like mdpopups and markdown dependency are missing.  I imagine during upgrade Package Control did something wrong and messed up those dependencies.

**Comment by Draghmar** [comment]
Hm...I know it probably isn't the place for asking this...but do you have suggestions how could I fix that dependency issues? I tried to download latest build of ST (dated at Feb 9) but it didn't fix it.

**Comment by stoivo** [comment]
Open command pallet and run `Package Control: install local Dependency`

**Comment by Draghmar** [comment]
It said that all dependencies are currently loaded. I also tried the one with satisfying dependency but this too didn't help me.

**Comment by facelessuser** [comment]
I would turn off Sublime and delete mdpopus and markdown if they exist in your user folder.  I would also navigate to the `Installed Packages` folder (which is in the same folder as `Packages`, and delete `0_package_control_loader.sublime-package` to force Sublime to rebuild a valid one (I've seen it get out of sync before).  I'd then run `Satisfy Dependencies` again.  Watch the console to make sure it is done, then restart Sublime.

**Comment by facelessuser** [comment]
Sorry updated post to reference correct folder.

**Comment by Draghmar** [comment]
Thanks a lot! It worked! Although ``Installed Packages`` are in the ``Data`` folder. I deleted anything related to ``mdpopup`` and ``markdown`` and the file you've mentioned and restarted ST after which did auto install missing dependencies and now ColorHelper works again!
- ST ver.: 3157
- Platform: windows
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
