### ISSUE TITLE
Error shown in console

### ISSUE THREAD

**Issue by princemaple** [facelessuser/ColorHelper#11]
```
Traceback (most recent call last):
  File "color_helper in C:\Users\Po\AppData\Roaming\Sublime Text 3\Installed Packages\ColorHelper.sublime-package", line 120, in on_navigate
  File "color_helper in C:\Users\Po\AppData\Roaming\Sublime Text 3\Installed Packages\ColorHelper.sublime-package", line 580, in show_colors
AttributeError: 'ColorHelperCommand' object has no attribute 'view_window'
```

**Comment by facelessuser** [comment]
This was a typo in the code on my part; should have been `view.window`.  I'll have a fix out tonight.

**Comment by princemaple** [comment]
:+1: thanks for the super fast reply

**Comment by facelessuser** [comment]
I just happened to be on github right now :smile:.

**Comment by princemaple** [comment]
Trying to avoid flushing your issue list here:

Is it supposed to show the color popup when I move the cursor to a color? (which I'm not seeing)

**Comment by facelessuser** [comment]
Yes, but if it crashed as your other issue indicated, it might not.  Currently it is confined to specific scopes as well.

**Comment by facelessuser** [comment]
Should be fixed in https://github.com/facelessuser/ColorHelper/releases/tag/st3-1.0.2 when available.

**Comment by princemaple** [comment]
This is fixed. However, I still don't see any popup when I move the cursor onto color code. No console errors.

**Comment by facelessuser** [comment]
Syntax language file used?  Example code?

**Comment by princemaple** [comment]
My files are suffixed with `.css` but I always use `SCSS` syntax highlighting.

**app.css**
```scss
$primary-color-dark:   #0277BD;
$primary-color:        #03A9F4;
$primary-color-light:  #4FC3F7;
$primary-color-text:   #212121;
$accent-color:         #E91E63;
$secondary-color-text: #000000;
$warn-color:           #FF5722;
$warn-color-text:      #FFFFFF;
$divider-color:        #B6B6B6;

@import "angular-csp";
@import "reset";
@import "appearance";
@import "layout";
@import "widgets";
@import "animations";

@import "home";
@import "upload";
@import "tests";
@import "authentication";
```

**Comment by facelessuser** [comment]
What is the syntax file package?  Look in the settings file.  You will see that I have syntax scope configuration there.  In order for this to work in your file, support needs to be added.

**Comment by princemaple** [comment]
Right. I use the `SCSS` package with some customization, nothing to do with scopes though. 

```
Scope:                         source.scss
                               meta.set.variable
                               constant.other.color.rgb-value.scss
                               punctuation.definition.constant.scss
```

**Comment by facelessuser** [comment]
In your settings add:
```js
"supported_syntax": [
    "source.sass constant.other.rgb-value.sass",
```

**Comment by facelessuser** [comment]
I should say add it to the others.  Just copy and paste the array to your user version, and add the new entry.

**Comment by facelessuser** [comment]
You can maybe omit `source.sass` and just use `constant.other.rgb-value.sass`.

**Comment by princemaple** [comment]
Getting weird errors. I'll have to get back to this later, need to head out now. Thanks for the help!

**Comment by facelessuser** [comment]
It's cool, I tried it out before I suggested it.  It worked for me.

**Comment by princemaple** [comment]
Yep, works now! Thanks heaps for this amazing tool. Loving it.
