### ISSUE TITLE
Support in sublime-color-scheme

### ISSUE THREAD

**Issue by qiacoucc** [facelessuser/ColorHelper#112]
Why does ColorHelper not support [.Sublime-color-scheme] suffix? Is it possible to provide technical support?

**Comment by facelessuser** [comment]
Just haven't got around to it.  It's possible, but I need to get around to it. When I do get around to it, it will support all the color except probably color names as the named colors format is different in CSS.  Sublime-color-scheme uses CSS color names in the CSS portion and uses x11 color names everywhere else.  I haven't had the chance to abstract the differences yet.

Anyways, when I get a chance I'll add it.

**Comment by qiacoucc** [comment]
OK, thank you! Look forward to the update
 
------------------ Original ------------------

**Comment by facelessuser** [comment]
@gir-bot add T: feature, P: maybe

**Comment by facelessuser** [comment]
This issue will be closed as a duplicate for the more generalized feature request #141 

@gir-bot add S: duplicate
