### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by ninja542** [facelessuser/ColorHelper#114]
I am not sure how to correct the package settings, but I would like to enable color helper on .sublime-color.schemes since that is the new file format for sublime text color schemes.

Will this be updated on the package or will I have to fiddle with the package settings myself?

**Comment by facelessuser** [comment]
Maybe both. The plan is to add support, but this hasn't made it to the top of my priority list. I've been very busy, and when I do have time, other projects or features have taken higher priority.

**Comment by ninja542** [comment]
ah ok that's fine

Should I close this issue?

**Comment by facelessuser** [comment]
Closing issue as this is a duplicate #112 

@gir-bot add S: duplicate
