### ISSUE TITLE
Ideas: Backgorund / Hover

### ISSUE THREAD

**Issue by kanlukasz** [facelessuser/ColorHelper#116]
## Ideas
I have two small ideas and i decided that I will share them with you

## 1st option:
Show background color on color value

## 2nd option:
Show the color only by hovering over the value

## Example (pic from ColorHighlighter)
![687474703a2f2f73616d65746d61782e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031332f30342f68696c696768742d636f6c6f722e676966](https://user-images.githubusercontent.com/30685349/49462000-4e72e180-f7f5-11e8-8f0a-651fc5693d11.gif)

## Question: 
What do you think about this? Is any chance to make it in some time :)?

**Comment by facelessuser** [comment]
ColorHighlighter already exists for this behavior. I do not think ColorHelper will will be implementing this.

**Comment by kanlukasz** [comment]
I'm not sure if we understand each other well - is ColorHighlighter already have function of recognizes the color by highlighting the value? How can I enable it?

**Comment by kanlukasz** [comment]
Yes you right of course, but ColorHighlighter not working with ST 3.1.1 [3176] and that's the problem :(

**Comment by kanlukasz** [comment]
You right its working, my post before was a completely mistake
Anyway like i sad  ColorHighlighter not working with ST 3.1.1 [3176] and that's the problem :(
