### ISSUE TITLE
4 or 8 digit hex color codes are not recognized

### ISSUE THREAD

**Issue by MaxValue** [facelessuser/ColorHelper#118]
## Description
Hexadecimal color codes using exactly 4 digits/places are not recognized in Sublime Text Buffers. E.g.:
`#0000` which would mean "complete transparency".

Those 4 digit codes are valid color codes in CSS.

## Support Info
I am using Sublime Text v3.1.1 build 3176 with ColorHelper v2.5.1

- ST ver.: 3176
- Platform: linux
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.4
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open a source file with color codes inside. The codes with 3 or 6 digits should get recognized.
2. Type in a color code with exactly 4 digits. E.g.: `#F00F` (should equal to pure red).
3. See that the plugin does not recognize the correctly written color code and does not draw a color box.

This issue is kinda related to #26, but this is the reverse: Detecting compressed codes.

**Comment by facelessuser** [comment]
That is a CSS4 color convention. You'd have to enable CSS4 colors: http://facelessuser.github.io/ColorHelper/usage/#color_scanningallowed_colors.

**Comment by MaxValue** [comment]
Ah I see! Thanks for the doc link! But:

I altered my user preferences for the plugin like this:

```JSON
{
    "allowed_colors": ["css4", "hex_compressed", "hexa_compressed"]
}
```

I know `hex_compressed` and `hexa_compressed` is included in `css4`, but the plugin still didn't recognize 4-digit hex colors (`hexa_compressed`).

I even tried it only with `hexa_compressed` enabled, but it still didn't recognized the 4-digit codes (it recognized 6-digit hex codes (`hex`), although I restarted Sublime Text in between changing settings).

**Comment by facelessuser** [comment]
Can you post your entire User settings for the plugin?

**Comment by MaxValue** [comment]
Here you go!:
```JSON
// Settings in here override those in "ColorHelper/color_helper.sublime-settings",

{
    "allowed_colors": ["hexa_compressed"],
}
```

**Comment by facelessuser** [comment]
Hmm.  That is what I thought it would be.  You need to copy the whole `color_scanning` object and then change what you want to override.  We currently don't have selective sub-key overrides.

```js
{
    // Scanning rules
    "color_scanning": [
        {
            "syntax_files": [],
            "syntax_filter": "whitelist",
            "base_scopes": [
                "source.css",
                "text.html"
            ],
            "scan_scopes": [
                // https://packagecontrol.io/packages/CSS3
                "meta.declaration-list.css -support.type.property-name.css -comment -string",
                // CSS, CSS in HTML etc. (based on: Sublime Default)
                "meta.property-value.css -comment -string",
                // CSS3, CSS3 in HTML etc. (based on: https://packagecontrol.io/packages/CSS3)
                "meta.value.css -comment -string",
                // HTML attributes (based on: Sublime Default)
                "meta.tag.inline.any.html string.quoted -constant.character.entity.html",
                "meta.tag.any.html meta.attribute-with-value.style.html"
            ],
            "scan_completion_scopes": [],
            "extensions": [],
            "allowed_colors": ["css4"],  // <-- change this
            "use_hex_argb": false,
            "compress_hex_output": true
        },
        /* Rest of the rules  */
   ]
}

**Comment by MaxValue** [comment]
Ah I see! Thank you _very much_ for the quick help!! It works now perfectly :relaxed:

I have 2 last questions:

- Why is `css3` the default in all the definitions? Can you make `css4` the default, since the browsers (and I guess other interpreters too) recognize the compressed formats?
- Could you write this info you gave me at the beginning of the `color_scanning` documentation (the part that a user would have to copy the whole substructure to the user settings)? This would help/prevent others from making the same mistake as me.

**Comment by facelessuser** [comment]
CSS3 made since at the time. All the colors were not supported fully in browsers at the time as I recall.

When I have time, if it isn't already present, I'll try to make the `color_scanning` behavior more clear.

**Comment by facelessuser** [comment]
CSS Color level 4 will be enabled by default for HTML/CSS/SCSS/SASS moving forward.
