### ISSUE TITLE
Hex 4 digit issues

### ISSUE THREAD

**Issue by FeBe95** [facelessuser/ColorHelper#120]
First of all: thank you for another outstanding plugin. As always: a plugin made by you is the best option out there!

## Description

Everything is working fine for me except the handling of 4-digit hex colors. The preview-phantoms display incorrect color/alpha combinations, the popups show weird color conversions and actually converting the colors results in invalid colors (e.g. clicking the second *wrong* option `#ff0000` results in the 5-digit hex color `#ff000`). The alpha levels in the rgba/hsla notations are completely off:

![grafik](https://user-images.githubusercontent.com/7470739/54637229-6f033680-4a88-11e9-9b8b-db26e4a123b5.png)

8-digit hex colors are working fine:
![grafik](https://user-images.githubusercontent.com/7470739/54637234-732f5400-4a88-11e9-9e19-aa115fe3ad5a.png)

I tried to keep the setup as simple as possible for this, creating a new plain text file and setting up the plugin like this:
```json
{
    "color_scanning": [
        {
            "syntax_files": [],
            "syntax_filter": "whitelist",
            "base_scopes": ["text.plain"],
            "scan_scopes": ["text.plain"],
            "scan_completion_scopes": [],
            "extensions": [],
            "allowed_colors": ["all"],
            "use_hex_argb": false,
            "compress_hex_output": true
        },
    ],
}

```

Toggling `compress_hex_output` or `use_hex_argb` and changing `allowed_colors` to just `hexa` doesn't make a difference.

There is no special console output while working with hexa colors. Every time a color gets rendered or I click something the following error gets printed to the console though. That might be another issue, as it gets printed with every color-notation, possibly because `hwb` fails with every color-notation:
```
mdpopups: Failed to convert/retrieve scheme to CSS!
```

## Support Info

- ST ver.: 3200
- Platform: windows
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.4.0
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. enable at least the `hexa_compressed` color-syntax
2. choose any language where ColorHelper is enabled
3. write some code containing 4-digit hex colors
4. experience your code in a new super-colorful way :)

**Comment by facelessuser** [comment]
This is definitely a confirmed bug.

**Comment by facelessuser** [comment]
Sorry it took so long to get to this, but it will be fixed in the next version
