### ISSUE TITLE
Breaking BracketHighlighter's "scope_brackets"

### ISSUE THREAD

**Issue by jfcherng** [facelessuser/ColorHelper#125]
Usually BH's "scope_brackets" works fine:
![image](https://user-images.githubusercontent.com/6594915/63408444-a607ba80-c421-11e9-9102-5ef9d7a32b4a.png)

But if there is a phantom next to a "scope_brackets", then the scope seems to be broken:
![image](https://user-images.githubusercontent.com/6594915/63408447-a7d17e00-c421-11e9-9323-3d9721245a2d.png)

Hmm... This looks more like a ST's bug actually.

The workaround can be moving the phantom to be out of "scope_brackets" if it's next to it.
which looks like this ![image](https://user-images.githubusercontent.com/6594915/63408892-95a40f80-c422-11e9-928e-98481a4d5c4c.png)

**Comment by facelessuser** [comment]
Yeah, this is a bug with Sublime. I'm not quite sure how to fix this. You can move the phantom to the left with https://github.com/facelessuser/ColorHelper/blob/master/color_helper.sublime-settings#L39, but that might just cause the right quote to not highlight.. 

Phantoms should be invisible when processing text and scope. Sublime needs to fix this.

**Comment by jfcherng** [comment]
God, it seems that someone had filed an issue in 2016 already.
https://github.com/SublimeTextIssues/Core/issues/1497

**Comment by facelessuser** [comment]
I have only one real complaint about Sublime, and that is how they handle bugs. There are a lot of these little things that never get addressed. Eventually this kind of stuff adds up...death by 1000 paper cuts.
