### ISSUE TITLE
Color Panel Background (ColorHighlighter plugin breaking convention)

### ISSUE THREAD

**Issue by enkia** [facelessuser/ColorHelper#13]
I'm having an odd display issue:
![Color Palette Screenshot](http://i.imgur.com/TKDvYdX.png)

I'm using ST3 on El Capitan with [`"theme": "Material-Theme-Darker.sublime-theme",`](http://equinusocio.github.io/material-theme/)

**Comment by facelessuser** [comment]
What color scheme are you using?  The theme doesn't affect background, but the color scheme does.

**Comment by enkia** [comment]
The problem seems to have corrected itself. The background is now black. Anyway, in case you still want to know, I'm using a [modified version](https://drive.google.com/file/d/0By3gHRVGUIYLcENZVzJQYWM2eTQ/view?usp=sharing) of [Predawn](https://github.com/jamiewilson/predawn) which has been further automatically modified by [Sublimelinter.](https://github.com/SublimeLinter/SublimeLinter3)

**Comment by facelessuser** [comment]
Yeah, SublimeLinter may be partly to blame.  I wish they would allow the theme modification to be turned off, but I digress.

Anyways, one reason the incorrect might stick around for a little is you that the tooltip themes get cached.  See configuring the cache settings for `mdpopups` here http://facelessuser.github.io/sublime-markdown-popups/usage/#global-user-settings.

I would keep an eye on it, and if you can predictably notice a pattern, let me know, and mabye we can mitigate the problem in the future.

**Comment by PixelT** [comment]
+1
I have this same issue... color of tooltip background is random (one time blue, one time red, another time another color)

**Comment by facelessuser** [comment]
> +1
I have this same issue... color of tooltip background is random (one time blue, one time red, another time another color)

I believe the issue is happening, but what I need is new information to solve this.

The background is read from your color scheme.  Do you have **any** plugins installed that modify the original color scheme, or that create a scheme that looks similar to the popup?  It is getting the background from a color scheme and what I need to know is how.  I have been using this plugin for months and months before release and have never seen this, so something is different about your setups.

You can decrease the cache to cause it to refresh more often to clear it quicker, but I can't solve this until I can reproduce it.

**Can you post all the plugins you have installed?**

**Comment by enkia** [comment]
The blue background came back this morning.
![Red this time](http://i.imgur.com/TdQpxcA.png)

 In addtion to SublimeLinter, [Color Highlighter](https://packagecontrol.io/packages/Color%20Highlighter) may be the culprit as well. It highlights colors like so:
![http://i.imgur.com/fGOsxnJ.png](http://i.imgur.com/fGOsxnJ.png)

**List of Packages:**
The ones marked in bold are ones I believe directly modify the editor by adding colored objects in some way.

* AdvancedNewFile
* BetterFindBuffer
* **BracketHighlighter**
* Can I Use
* **Color Highlighter**
* ColorHelper
* **ColorSchemeEditor**
* Emmet
* Emmet CSS Snippets
* Gist
* **GitGutter**
* GitHub Flavored Markdown Preview
* HTML Page Snippets
* HTML CSS-JS Prettify
* Javascript Completions
* jQuery
* LESS
* Markdown Preview
* Material Theme
* Package Control
* Predawn (modified version of color scheme used)
* Predawn Twighlight Theme (not used)
* Sass
* SassBeautify
* SCSS
* SFTP
* SideBarEnhancements
* SublimeCodeIntel
* SublimeGit
* **SublimeLinter**
* **SublimeLinter-jshint**
* **SublimeLinter-php**
* SyncedSideBar
* Tag
* Terminal
* Theme - Flatland (not used)

**That *was* my list of installed packages but I've since removed:**

* ColorSchemeEditor

I checked Color Helper after removing ColorSchemeEditor and background is back to black.

**Comment by FreezeFire70** [comment]
Hi,
ColorHighlighter (https://github.com/Monnoroch/ColorHighlighter) is causing this issue. Sorry, but I have no clue how to solve it.

**Comment by facelessuser** [comment]
@enkia Thanks, this will hopefully be of great help to tracking down what is going on.

- BracketHighlighter is fine and does not modify the color scheme (it's my package so I know it isn't the culprit :smle:).
- I do use SublimeLinter, but I am doubting it is the culprit as it's changes look benign (they annoy me, but are benign), but I will look into it more.

@FreezeFire70.  I will take a look at what ColorHighlighter is doing.  If this is the culprit, I may have a solution by the weekend.

**Comment by enkia** [comment]
Removing ColorSchemeEditor didn't help, actually so I'm with FreezeFire70 -  must be ColorHighlighter.

**Comment by facelessuser** [comment]
https://github.com/Monnoroch/ColorHighlighter is totally the culprit.  Man that thing is nasty...it butchers the format.  I see exactly why its breaking.  Ugghh.  But l also see how I can avoid its nonsense.

Thanks for the help guys.

**Comment by enkia** [comment]
Yeah, coming from a user's point of view, Color Highlighter is pretty buggy. I have it set to highlight using an underline so that when it does bug out, it's only minimally distracting and usually closing the file and re-opening solves the problem. It's insanely useful for my work though, so I deal with it.

**Comment by facelessuser** [comment]
I completely understand.  I'm probably being a little hard on it.  At least this will make my scheme parsing more robust.

**Comment by PixelT** [comment]
Maybe it will be easiest, when @Monnoroch fixes something in https://github.com/Monnoroch/ColorHighlighter which causes error?

**Comment by facelessuser** [comment]
Basically the global settings should be first, but ColorHighlighter breaks this...but it is valid.  I think he should fix it, but I should also scan for this as well.  So it is in my best interest to ensure I can parse all valid schemes.  There may be another plugin in the future that does this, so I need to be prepared.

**Comment by facelessuser** [comment]
This should fix the issue: https://github.com/facelessuser/sublime-markdown-popups/releases/tag/1.1.3.

I don't know how long it will take for your Package Control install to see the dependency is not up to date.  You can try running the command "Satisfy Denpendencies"  and see if Sublime updates `mdpopups` (restart may be required).  But when it does, this should be cleared up.

**Comment by Monnoroch** [comment]
Hi all!
What seems to be the problem with CH?

**Comment by facelessuser** [comment]
@Monnoroch Not really a problem per se.  It caught me off guard that you inject ColorHelper specific scope definitions in your color schemes **before** the global settings.

I have a fix in for detecting and handling this now, but globals should be first as those colors are used to blend colors down the line, but your modified color schemes are technically valid.  For speed in parsing, you shouldn't have to loop the whole scheme file to find the globals first.

**Comment by enkia** [comment]
It's not up yet on Package Control but I went ahead and installed the update and it solved the issue. I can actually tell because the popup is using my theme's background which it hadn't before. (I mistakenly thought it was fixed when I saw the random background turn black.)

Thanks for putting in a fix for this so quickly. Great addon, btw!

**Comment by facelessuser** [comment]
No matter how much I test things, there is always some corner case I didn't think of :smile:.

> Thanks for putting in a fix for this so quickly. Great addon, btw!

Glad you like!
