### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by luckman212** [facelessuser/ColorHelper#169]
Congratulations & thank you for the monumental 3.0 release! 🎉 

I was just reading the Docs and noticed a small typo, here
https://facelessuser.github.io/ColorHelper/settings/rules/#sytnax_files (`sytnax -> syntax`)

![image](https://user-images.githubusercontent.com/1992842/110878260-e00d0b80-82a8-11eb-94cb-cdecfbfed4eb.png)

**Comment by facelessuser** [comment]
🤦 And my spellchecker didn't catch it because I ignore inline code.

**Comment by facelessuser** [comment]
Docs regenerated. Should be live soon.
