### ISSUE TITLE
There is no Quick Start Guide

### ISSUE THREAD

**Issue by ilyakam** [facelessuser/ColorHelper#179]
## Description

The message that PackageControl surfaces from this plugin says that there's supposed to be a "Quick Start Guide." But per the screenshot below, there is no such guide in the settings.

<img width="1439" alt="there is no quick start guide" src="https://user-images.githubusercontent.com/183227/113207909-0da10100-9226-11eb-80c7-340c8d4c47f9.png">

## Support Info

<img width="488" alt="support info" src="https://user-images.githubusercontent.com/183227/113208760-06c6be00-9227-11eb-8220-474644c04cf7.png">
(This is a little meta, but despite what it says at the bottom of that box, the info wasn't copied to the clipboard.)

## Steps to Reproduce Issue

1. Install ColorHelper via PackageControl
2. Receive misleading message

**Comment by facelessuser** [comment]
Yeah, there is no quick start guide for Color Helper. I never got around to creating one.

I support a number of Sublime plugins, so I have a similar infrastructure for my plugins which at times get copied and pasted when creating a new one. I must have copied from a project that had a quickstart guide when I created ColorHelper, but didn't remove the message from the install notice. I'll clean that up in the next release.

Thanks for reporting!

@gir-bot remove S: triage
@gir-bot add T: maintenance, C: docs
