### ISSUE TITLE
Enhancements in popup

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#18]
*) Ihmo the font size by default should be greater than now... or as a setting property maybe?

![font size](http://i.imgur.com/ZmreYTR.png)

*) When I write code (hardcode, not select from palete/picker) in hex, the popup doesn't automatically close.

http://i.imgur.com/gzmzERh.gifv

**Comment by facelessuser** [comment]
Next release should auto close the popup when ignored while typing.  Link fonts are larger, but again, these can be overridden by a user if they desire.
