### ISSUE TITLE
No settings option to output uppercase hex colors

### ISSUE THREAD

**Issue by MattDMo** [facelessuser/ColorHelper#180]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ColorHelper/) related to your specific question, issue, or request.

---

## Description

... what is the issue / request ?

#74 was an issue with `"upper_case_hex": true` not working in the 2.x series, and it was fixed by 4d03c04. However, that code seems to have been completely removed in 3.x. I fixed it by editing [line 62 in `custom/ahex.py`](https://github.com/facelessuser/ColorHelper/blob/037be373f9bde29353a99b949557aae893224325/custom/ahex.py#L62) to the following:

```
template = "#{:02X}{:02X}{:02X}{:02X}" if show_alpha else "#{:02X}{:02X}{:02X}"
```
(changing the lowercase `{:02x}`s to `{:02X}`).

This won't work for everyone, as it now forces *all* hex output to be uppercase. Adding extra code to look for `"upper_case_hex"` in the settings as well as in the parameters passed to the function hopefully won't be too difficult, I just haven't had a chance to do it yet.

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

...

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

- ST ver.: 4099
- Platform: windows
- Arch: x64
- Plugin ver.: 3.3.1
- Install via PC: True
- mdpopups ver.: 4.1.1
- markdown ver.: 3.2.2
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. First step...
2. Second step...
3. Third step...

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
No not removed, just different.

Here we override the `css-level-4` color class options to export hex with uppercase.

```js
    "user_color_classes": {
        "css-level-4": {
            "output": [
                {"space": "srgb", "format": {"hex": true, "upper": true}}, // <--- make hex upper case
                {"space": "srgb", "format": {"comma": true}},
                {"space": "hsl", "format": {"comma": true}},
                {"space": "hwb", "format": {"comma": false}},
                {"space": "lch", "format": {"comma": false}},
                {"space": "lab", "format": {"comma": false}},
                {"space": "display-p3", "format": {}},
                {"space": "rec2020", "format": {}},
                {"space": "prophoto-rgb", "format": {}},
                {"space": "a98-rgb", "format": {}},
                {"space": "xyz", "format": {}}
            ]
        }
    },
```

@gir-bot remove s: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
String output options are discussed in [`coloraide` documentation](https://facelessuser.github.io/coloraide/strings/). ColorAide is used to provide color conversion, CSS string parsing, and CSS output.

**Comment by facelessuser** [comment]
I should probably do a better job at documenting this area... 🤔

**Comment by facelessuser** [comment]
I'm sorry, I see you are are talking about ahex, so maybe update `argb` color class.

I also need to rename the color class `0xahex` to `0xhex`...that was a typo.

**Comment by facelessuser** [comment]
I think I'll add a FAQ section in the docs that explains things like this a bit more. I imagine this will be a somewhat common question.

**Comment by MattDMo** [comment]
So I put this in my user settings:
```
    "user_color_classes":
    {
        "css-level-4": {
            "output": [
                {"space": "srgb", "format": {"hex": true, "upper": true}}, // <--- make hex upper case
            ]
        }
    }
```
but it's still outputting lowercase.

![image](https://user-images.githubusercontent.com/1776358/113324967-bebaa080-92e5-11eb-9417-99ee938b4bd9.png)


This is a `.sublime-color-scheme` file, if it matters.

**Comment by facelessuser** [comment]
I need maybe some more info. Looks like you are using color schemes? If so, you'll want to specify `sublime-colormod` as the color class, and provide all the output options. It overrides at the top level (`output`) not down at the individual level of each value in `options`.

**Comment by facelessuser** [comment]
For clarity:

```js
        "sublime-colormod": {
            "output": [
                {"space": "srgb", "format": {"hex": true, "upper": true}},
                {"space": "srgb", "format": {"comma": true, "precision": 3}},
                {"space": "hsl", "format": {"comma": true, "precision": 3}}
            ]
        },
```

**Comment by MattDMo** [comment]
That doesn't seem to be working either...

**Comment by facelessuser** [comment]
Let me confirm as I confirmed the first example worked.

**Comment by facelessuser** [comment]
Settings:

```js
    "user_color_classes": {
        "sublime-colormod": {
            "output": [
                {"space": "srgb", "format": {"hex": true, "upper": true}},
                {"space": "srgb", "format": {"comma": true, "precision": 3}},
                {"space": "hsl", "format": {"comma": true, "precision": 3}}
            ]
        }
    },
```

Results:

<img width="493" alt="Screen Shot 2021-04-01 at 10 51 52 AM" src="https://user-images.githubusercontent.com/1055125/113327598-64671300-92d8-11eb-80cf-95ba46b4c567.png">

**Comment by facelessuser** [comment]
@MattDMo please let me know what you are editing files in. What the rule for the file you are editing looks like.

Your screenshot looks like a `sublime-color-scheme` file which is why I suggested `sublime-colormod`, but then you mentioned in the opening post you modified `ahex.py`, so I don't know which rule to color class to suggest you edit.

**Comment by facelessuser** [comment]
Also, check out https://github.com/facelessuser/ColorHelper/pull/182 which has a draft that explains all of this a bit better and maybe will help you figure out what you are getting wrong.

**Comment by MattDMo** [comment]
OK, I got it. It was an issue with braces in my settings, the `"sublime_colormod"` key ended up syntactically being outside of `"user_color_classes"`. It's working great now, thanks!

I'll check out #182 when I get a chance.
