### ISSUE TITLE
Error in color picker

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#20]
When I click on picker, in console I have:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "color_helper_picker in [ST path]/Installed Packages/ColorHelper.sublime-package", line 262, in run
  File "color_helper_picker in [ST path]/Installed Packages/ColorHelper.sublime-package", line 59, in get_color_map
TypeError: color_box() got an unexpected keyword argument 'alpha'
```

**Comment by facelessuser** [comment]
You need mdpopups [`1.2.0`](https://github.com/facelessuser/sublime-markdown-popups/releases/tag/1.2.0).  Package Control seems to not always update things when they need to be.  Or maybe you just need a restart.  Run the Package Control "Satisfy Dependency" command and restart.  It should fix it.

**Comment by PixelT** [comment]
OK, run Satisfy Dependency do that job - thanks.
One more thing - When I select color from picker, I think it will be good, if I can insert the code of color using >>> displayed in each type (hex, rgb, hsl, etc.) like as in simple color popup

**Comment by facelessuser** [comment]
> OK, run Satisfy Dependency do that job - thanks.
One more thing - When I select color from picker, I think it will be good, if I can insert the code of color using >>> displayed in each type (hex, rgb, hsl, etc.) like as in simple color popup

Currently, the color picker just accepts a color `#RRGGBBAA` calls a sublime command callback by passing in the a color `#RRGGBBAA`.  Currently that callback is ColorHelperCommand which doesn't yet have a way to specify a convert option directly when calling.  Please open up a new issue describing this desire, and I will look at it sometime in the future.

>Another thing - no picker option when I started writing the color (for exmaple when write # / rgba() and the popup will show).

Please specify the language package when describing issues like this.  I imagine you are referring to SCSS, but please confirm.  I imagine I have restricted the scope a bit too much.  I will see what I can do in the next release.  Please open up a new issue describing this issue.

It is hard for me to track issues when I have one issue describing multiple issues.

**Comment by facelessuser** [comment]
Next release will fixes the issue for # / rgba().  I added a new setting for incomplete color scopes.  That we can compare incomplete scopes for the auto popup, but not scan all those scopes for when indexing the colors in a file.

**Comment by facelessuser** [comment]
> One more thing - When I select color from picker, I think it will be good, if I can insert the code of color using >>> displayed in each type (hex, rgb, hsl, etc.) like as in simple color popup

This will be in the new version coming probably this weekend.

**Comment by facelessuser** [comment]
It has all been released...hopefully there are no regressions...
