### ISSUE TITLE
Sliders in picker no longer available

### ISSUE THREAD

**Issue by maegul** [facelessuser/ColorHelper#226]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ColorHelper/) related to your specific question, issue, or request.

---

## Description

The `sliders` option in the `picker` window no longer provides the `sliders` interface and instead raises an exception (extracted below ... `AttributeError: 'Color' object has no attribute 'hue'`)

![Untitled](https://user-images.githubusercontent.com/13930443/183328288-5b1fcc63-357f-4f24-b30f-e92ced0ee284.png)

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_picker.py", line 769, in run
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_picker.py", line 495, in get_channel
AttributeError: 'Color' object has no attribute 'hue'
```

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

...

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

- ST ver.: 4131
- Platform: osx
- Arch: x64
- Plugin ver.: 5.0.1
- Install via PC: True
- mdpopups ver.: 4.2.2

## Steps to Reproduce Issue

1. Click color preview swatch
2. Click `picker`
3. Click `sliders`
4. Check console for exception

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
I'm pretty sure I know what the issue is. The underlying color library was upgraded and I missed a few changes in the code to accommodate the new version.

I'll try and get a fix out tomorrow.

**Comment by facelessuser** [comment]
I see why I missed it, the access was a bit more abstracted, so it eluded my grep.
