### ISSUE TITLE
Tools such as Edit and Mix are broken

### ISSUE THREAD

**Issue by maegul** [facelessuser/ColorHelper#230]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ColorHelper/) related to your specific question, issue, or request.

---

## Description

... what is the issue / request ?

* Attempting to use a color helper tool such as `Edit and Mix` fails with the exception below (this particular one from the `Color Info popup`).
* This is the same for attempts at accessing from `Color Info popup`, Context Menu and Command Palette, all returning almost identical tracebacks.

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
TypeError: run() missing 1 required positional argument: 'color_helper_edit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1419, in create_input_handler_
    return self.input(args)
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_tool_edit.py", line 303, in input
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_tool_edit.py", line 179, in __init__
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_tools.py", line 59, in __init__
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_mixin.py", line 23, in setup_gamut_style
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
TypeError: run() missing 1 required positional argument: 'color_helper_edit'
```
> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

- ST ver.: 4131
- Platform: osx
- Arch: x64
- Plugin ver.: 6.0.3
- Install via PC: True
- mdpopups ver.: 4.2.2

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

## Steps to Reproduce Issue

1. Open `Color Info` popup from preview swatch
2. Click `Tools`
3. Click `Edit and Mix`

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
I am not experiencing this issue.

**Comment by facelessuser** [comment]
I may need more info. Is this occurring in a particular file type?

**Comment by facelessuser** [comment]
```
  File "/Users/errollloyd/Library/Application Support/Sublime Text/Installed Packages/ColorHelper.sublime-package/ch_mixin.py", line 23, in setup_gamut_style
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

This seems like something went wrong with Sublime, not ColorHelper. If we look at the line in question, this is Sublime's plugin API:

```py
    def setup_gamut_style(self):
        """Setup the gamut style."""

        ch_settings = sublime.load_settings('color_helper.sublime-settings')
```

If `sublime` is `None`, then something big went wrong with the whole plugin system. I'd try and restart Sublime. Worst case, uninstall ColorHelper, and try to reinstall it.

**Comment by facelessuser** [comment]
I did push an update this evening to fix a small issue with custom Color objects. Maybe after Sublime updated your plugin, the plugin state went bad. I imagine a restart is all that is needed. I ran this in a clean, portable Sublime, and everything is working as expected.

**Comment by maegul** [comment]
Yep ... I didn't see that an update had come through.  Works just fine!  Sorry for the hassle!!

**Comment by facelessuser** [comment]
Yeah, to not annoy people, I don't post messages on bug fix releases as all those package control messages can get annoying, especially in times when numerous releases are getting pushed (like recently).

Unfortunately, even bug fix releases can sometimes cause certain parts of the plugin not to reload properly after an update, especially ones with deeply nested source. It's the downside of plugins getting patched on the fly. Simple plugins with a single source file usually update with little to no issues, but ColorHelper is far more complex than that.
