### ISSUE TITLE
hint not working 

### ISSUE THREAD

**Issue by alvarolm** [facelessuser/ColorHelper#232]
## Description

... what is the issue / request ?

color hints not working

> For bugs and support questions:

expected to see a color hint next to the color definition
right click menu seems to work as expected
don't see any errors
![image](https://user-images.githubusercontent.com/2561547/189568998-b6ad4737-4bdf-4f9b-9f10-8cdf597ba399.png)
![image](https://user-images.githubusercontent.com/2561547/189569127-aaa1db1d-dc5c-4f0a-95df-2f786d1d3d88.png)
![image](https://user-images.githubusercontent.com/2561547/189569166-50eda869-f9c9-42e8-bb08-4c300bb440a9.png)

## Support Info

- ST ver.: 4126
- Platform: linux
- Arch: x64
- Plugin ver.: 6.0.3
- Install via PC: True
- mdpopups ver.: 4.2.2

## Steps to Reproduce Issue

1. open any tmTheme file

thanks in advance

**Comment by facelessuser** [comment]
Working here with a fresh install of 4126 and ColorHelper:

<img width="392" alt="Screen Shot 2022-09-11 at 9 56 56 PM" src="https://user-images.githubusercontent.com/1055125/189571256-4ec2a94e-9e20-427f-9bc8-a56d0cd4bccf.png">

So, my question is are you using the default XML syntax or some other syntax? Are you using any ColorHelper settings overrides? Are you getting errors in the console?

From what I'm seeing, there are no issues.

**Comment by facelessuser** [comment]
Also, make sure you restart ST after installing (in case you haven't).

**Comment by alvarolm** [comment]
Have tried restarting and reinstalling multiple times, also I'm using the default syntax, tried with the default plugin settings and debug set to true, no visible errors from the console, seems very odd, here is all the console output:

> UI scale: 1.001 (gtk text scale)
> startup, version: 4126 linux x64 channel: stable
> executable: /opt/sublime_text/sublime_text
> application: /opt/sublime_text
> working dir: /home/user
> packages path: /home/user/.config/sublime-text/Packages
> state path: /home/user/.config/sublime-text/Local
> zip path: /opt/sublime_text/Packages
> zip path: /home/user/.config/sublime-text/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 0.363576
> startup time: 0.799958
> first paint time: 0.942393
> git: located Sublime Merge installed at /opt/sublime_merge
> git: using configuration from system git install
> git: tracking working dir /home/user/.config/sublime-text/Packages/LSP
> git: tracking working dir /home/user/dev/assets/go/src/sample/libs/storage/localdb
> git: tracking working dir /home/user/GoSublime
> git: tracking working dir /home/user/dev/assets/go/src/sample/apps/cryptokit
> git: tracking working dir /home/user/dev/assets/go/src/sample/libs/crypto
> git: tracking working dir /home/user/dev/assets/go/src/sample/libs/semver
> git: tracking working dir /home/user/dev/assets/go/src/sample/libs/app/buildinfo/test
> git: tracking working dir /home/user/dev/assets/go/src/sample/libs/tls/csrgenerator/cmd
> reloading plugin Default.arithmetic
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.colors
> reloading plugin Default.comment
> reloading plugin Default.convert_color_scheme
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.html_print
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading python 3.3 plugin 0_package_control_loader.00-package_control
> reloading python 3.3 plugin 0_package_control_loader.01-pygments
> reloading python 3.3 plugin 0_package_control_loader.10-wcwidth
> reloading python 3.3 plugin 0_package_control_loader.40-ptyprocess
> reloading python 3.3 plugin 0_package_control_loader.50-backrefs
> reloading python 3.3 plugin 0_package_control_loader.50-bracex
> reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
> reloading python 3.3 plugin 0_package_control_loader.50-pathlib
> reloading python 3.3 plugin 0_package_control_loader.50-pymdownx
> reloading python 3.3 plugin 0_package_control_loader.50-pyte
> reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
> reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
> reloading python 3.3 plugin 0_package_control_loader.50-typing
> reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
> reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
> reloading python 3.3 plugin 0_package_control_loader.55-wcmatch
> reloading python 3.3 plugin ayu.activation
> reloading python 3.3 plugin ayu.Icons
> reloading python 3.3 plugin BracketHighlighter.bh_core
> reloading plugin Default.keymap
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.rename
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.ui
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin ShellScript.ShellScript
> reloading plugin A File Icon.plugin
> reloading python 3.3 plugin BracketHighlighter.bh_logging
> reloading python 3.3 plugin BracketHighlighter.bh_plugin
> reloading python 3.3 plugin BracketHighlighter.bh_popup
> reloading python 3.3 plugin BracketHighlighter.bh_regions
> reloading python 3.3 plugin BracketHighlighter.bh_remove
> reloading python 3.3 plugin BracketHighlighter.bh_rules
> reloading python 3.3 plugin BracketHighlighter.bh_search
> reloading python 3.3 plugin BracketHighlighter.bh_swapping
> reloading python 3.3 plugin BracketHighlighter.bh_wrapping
> reloading python 3.3 plugin BracketHighlighter.support
> reloading python 3.3 plugin ColorHelper.ch_dev
> reloading python 3.3 plugin ColorHelper.ch_mixin
> reloading python 3.3 plugin ColorHelper.ch_native_picker
> reloading python 3.3 plugin ColorHelper.ch_panel
> reloading python 3.3 plugin ColorHelper.ch_picker
> reloading python 3.3 plugin ColorHelper.ch_preview
> reloading python 3.3 plugin ColorHelper.ch_tool_blend
> reloading python 3.3 plugin ColorHelper.ch_tool_colormod
> reloading python 3.3 plugin ColorHelper.ch_tool_contrast
> reloading python 3.3 plugin ColorHelper.ch_tool_diff
> reloading python 3.3 plugin ColorHelper.ch_tool_edit
> reloading python 3.3 plugin ColorHelper.ch_tools
> reloading python 3.3 plugin ColorHelper.ch_util
> reloading python 3.3 plugin ColorHelper.support
> reloading python 3.3 plugin GoGuru.goGuru
> reloading python 3.3 plugin GoTags.GoTags
> reloading python 3.3 plugin LSP-gopls.plugin
> reloading python 3.3 plugin LSP-gopls.types
> reloading python 3.3 plugin LSP-gopls.utils
> reloading python 3.3 plugin LSP-gopls.vulnerabilities
> reloading python 3.3 plugin Origami.origami
> reloading python 3.3 plugin Package Control.1_reloader
> reloading python 3.3 plugin Package Control.2_bootstrap
> reloading python 3.3 plugin Package Control.Package Control
> reloading python 3.3 plugin PackageResourceViewer.package_resource_viewer
> reloading python 3.3 plugin PackageResourceViewer.package_resources
> reloading python 3.3 plugin Terminus.main
> reloading python 3.3 plugin ColorPicker.sublimecp
> reloading python 3.3 plugin GoDebug.jsonrpctcp_client
> reloading python 3.3 plugin GoDebug.sdconst
> reloading python 3.3 plugin GoDebug.sdlogger
> reloading python 3.3 plugin GoDebug.sdmain
> reloading python 3.3 plugin GoDebug.sdobjecttype
> reloading python 3.3 plugin GoDebug.sdview
> reloading python 3.3 plugin GoDebug.sdworker
> reloading python 3.3 plugin HTML-CSS-JS Prettify.HTMLPrettify
> reloading python 3.3 plugin LSP.boot
> plugins loaded
> GoGuru: ('debug:', True)
> GoGuru: ('use_golangconfig', False)
> GoGuru [DEBUG]: ('git return code', 128)
> GoGuru [DEBUG]: ("couldn't get git tag:", <class 'Exception'>)
> GoGuru: ('version:', '0.1.22')
> LSP: enabled configs: gopls
> LSP: disabled configs: clangd, erlang-ls, ocaml, polymer-ide, ruby, rust-analyzer, sorbet
> LSP: view 14 has no syntax
> Package Control: No updated packages
> Unable to open /home/user/.config/sublime-text/Packages/ColorHelper/color_helper.sublime-settings
> reloading settings Packages/User/color_helper.sublime-settings
> LSP: starting ['/home/user/.cache/sublime-text/Package Storage/LSP-gopls/bin/gopls'] in /home/user/dev/assets/go/src/sample
> LSP: gopls: Supported execute commands: ['gopls.add_dependency', 'gopls.add_import', 'gopls.apply_fix', 'gopls.check_upgrades', 'gopls.edit_go_directive', 'gopls.gc_details', 'gopls.generate', 'gopls.generate_gopls_mod', 'gopls.go_get_package', 'gopls.list_imports', 'gopls.list_known_packages', 'gopls.regenerate_cgo', 'gopls.remove_dependency', 'gopls.run_tests', 'gopls.run_vulncheck_exp', 'gopls.start_debugging', 'gopls.test', 'gopls.tidy', 'gopls.toggle_gc_details', 'gopls.update_go_sum', 'gopls.upgrade_dependency', 'gopls.vendor']
> LSP: gopls: supported code action kinds: ['quickfix', 'refactor.extract', 'refactor.rewrite', 'source.fixAll', 'source.organizeImports']
> LSP: gopls: registering capability: didChangeConfigurationProvider

**Comment by facelessuser** [comment]
I'm going to need some more information or something as I simply cannot reproduce using a clean Sublime install.

```
- ST ver.: 4126
- Platform: osx
- Arch: x64
- Plugin ver.: 6.0.3
- Install via PC: True
- mdpopups ver.: 4.2.2
```

Do you have ColorHelper accidentally disabled in Package Control? Has it ever worked for you before now? Does this happen with all tmTheme files or just a very specific one, and if so, can you point me to the tmTheme file.

I do use ColorHelper on Linux, macOS, and Windows, and I've not seen any issues myself. I'm not discounting your issues, but it sounds like you have something local that is interfering. I'm not sure if that is other plugins, or what.

I would consider potentially disabling certain plugins to see if that allows things to start working. I'm just not sure what is different about your environment vs mine.

**Comment by alvarolm** [comment]
of course.

> Do you have ColorHelper accidentally disabled in Package Control? 
no, checked before and just stared disabling other packages thinking there may lay the culprit.

**Has it ever worked for you before now?**

no, I haven't seen hints working yet (will try with other file types), the color help commands work fine (color info, palettes etc), and the plugin seems to load perfectly in the console.

**Does this happen with all tmTheme files or just a very specific one, and if so, can you point me to the tmTheme file.**

Just checked with a css file, and it works as expected, while doing this just realized that in the lower right corner the syntax indicator appeared: "XMP (Plist)" happens with the command "UI: customize color scheme" changing to XML work as expected.

file source:
[https://pastebin.pl/view/4d617a9a](https://pastebin.pl/view/4d617a9a)

adding a color rule to consider xml plist resolves the issue:

```
        {
            "name": "XML (Plist)",
            "base_scopes": ["text.plist"],
            "color_class": "css-level-4",
            "scanning": [
                "text.plist -meta.tag.xml -comment -string, string.unquoted.cdata.xml"
            ]
        },
```

**Comment by alvarolm** [comment]
https://github.com/facelessuser/ColorHelper/compare/master...alvarolm:ColorHelper:patch-1

**Comment by facelessuser** [comment]
Okay, that makes much more sense.

**Comment by facelessuser** [comment]
It appears this is not a bug, but a currently unsupported syntax file, the exact syntax file remains to be declared.  Support for a specific syntax file can be requested (or better yet a PR issued). As this issue does not declare a specific syntax file, there is nothing for us to do at this time. I will leave the associated PR open for a little in the hopes that the actual plugin providing the syntax file will be discovered and declared, but if not, I will likely have to close the PR as well.
