### ISSUE TITLE
Add support for colors in quotes, like in .sublime-color-theme files

### ISSUE THREAD

**Issue by plocket** [facelessuser/ColorHelper#259]
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Before submitting an issue search past issues and read the area of the [documentation](http://facelessuser.github.io/ColorHelper/) related to your specific question, issue, or request.

---

## Description

Add support for colors in quotes, like in .sublime-color-theme files. For example:

```json
  "variables":
    {
        "black": "hsl(0, 0%, 0%)",
    }
```

> Vague issues/requests will be marked with `Insufficient Details` for about a week.  If not corrected, they will be marked `Stale` for about a week and then closed.

> For feature requests or proposals:

> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.

It would work the same way as in other locations - the color would appear next to the value (`"hsl(0, 0%, 0%)"` in this example)

> For bugs and support questions:

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.
> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

N/A

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

I can't even find "Package Settings" in package control. Maybe this is different in Sublime Text 4. The version of this package is 6.3.1

## Steps to Reproduce Issue

N/A

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
You mean like this?

<img width="675" alt="Screenshot 2023-11-23 at 1 45 03 PM" src="https://github.com/facelessuser/ColorHelper/assets/1055125/0fb64e66-184c-4030-84f3-23bd546e1b6e">

Currently, this is supported when using Sublime Package Dev: https://packagecontrol.io/packages/PackageDev.
That package scopes color schemes very well, and ColorHelper will highlight color previews in it.

**Comment by plocket** [comment]
Thank you!
