### ISSUE TITLE
module 'ColorHelper.lib.coloraide.algebra' has no attribute 'no_nan'

### ISSUE THREAD

**Issue by TechRoot** [facelessuser/ColorHelper#269]
Suddently, maybe because some update i were not aware, i can no longer use the color picker "slider" function.

Clicking such button throws the following error and makes color picker irresponsive until closed.
The following console error is given:

`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1698, in run_
    return self.run(edit, **args)
  File "C:\Users\alexc\AppData\Roaming\Sublime Text\Installed Packages\ColorHelper.sublime-package\ch_picker.py", line 786, in run
  File "C:\Users\alexc\AppData\Roaming\Sublime Text\Installed Packages\ColorHelper.sublime-package\ch_picker.py", line 505, in get_channel
AttributeError: module 'ColorHelper.lib.coloraide.algebra' has no attribute 'no_nan'`

## Support Info
- ST ver.: 4169
- Platform: windows
- Arch: x64
- Plugin ver.: 6.4.0
- Install via PC: True
- mdpopups ver.: 4.2.2

Issue video: 

https://i.imgur.com/uD1KdXM.gif

**Comment by facelessuser** [comment]
Hmm, looks like I may have missed a place when updating to the latest ColorAide.

**Comment by facelessuser** [comment]
The release has been tagged. Should be available on Package Control within the next 2 hours.

**Comment by TechRoot** [comment]
Thank you so much, this is very much appreciated. 💛
