### ISSUE TITLE
Color preview for Tailwind css

### ISSUE THREAD

**Issue by Yasinrabiee** [facelessuser/ColorHelper#274]
Thank you for development this package, just somthing, someone who use Talwind in their project, they just coding in html file and they don't switch with css file. 

In Tailwind we have a lots of class color for bg, text,  border and...

```html
<div class="border border-gray-200 dark:bg-gray-800 dark:border-gray-700 transition">
```

Is it possible set color preview for tailwind???

**Comment by facelessuser** [comment]
It's possible, but not out of the box. I don't use tailwind, so I don't know much about their custom color system.

In order for ColorHelper to support tailwind colors, someone would have to come up with a custom color object that can parse their colors to something more meaningful and export colors to this format.

Take note, that `bg-`, `border-` and such have no real meaning in colors, that is specifying UI stuff. The custom color object would need to grab only the color portions of these. You would need to adjust the regular expression when in tailwind to capture these colors, most likely using some kind of look behind to make sure the colors have the specified prefix (`bg-`, `border-`, etc.), but those should not be captured as they provide no meaningful color data and cannot be preserved during color translation to other spaces. 

Anyway, it is technically possible, but it needs some custom support, and I'm not very familiar with tailwind.

**Comment by Yasinrabiee** [comment]
That's right, Thank you for attention.
