### ISSUE TITLE
Palete with colors in current file

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#29]
Feature: automatically generate palette with colors which I used in current file

**Comment by facelessuser** [comment]
Isn't that what it already does (http://facelessuser.github.io/ColorHelper/usage/#enable_current_file_palette)?  The docs don't really sait it, but it should occur on file save (I should add that to the docs).

**Comment by facelessuser** [comment]
Was your question answered?  Or are you still having trouble?

**Comment by PixelT** [comment]
I tested it - for Windows is also OK (I have the pallete with current colors, but not all... (I need to test it again to make sure)
But on Mac, the ColorHelper doesn't work anymore... when I click on color e.g. #ddd the popup doesn't open anymore :( The console doesn't output anything error

**Comment by facelessuser** [comment]
I actually develop the plugins on a Mac, so I am not seeing these issues.  I would try to reinstall it.  Possibly run "Satisfy Dependency" command.  Restart Sublime after any of these steps.  But I have the most recent update and it is working fine for me on Mac.

**Comment by PixelT** [comment]
Now is show on Mac... (I nothing change...)
The palette colors should be show in 'Current colors'?
If yes, they only show max 5 color (I have more than 5 colors in my project)

**Comment by facelessuser** [comment]
Project or file?  Please clarify as current colors are just the colors in the current file.   Also,  post example CSS that exhibits the problem.

**Comment by PixelT** [comment]
I describe this situation (screen 1)

![](http://i.imgur.com/Sna2pGj.png)

Only 5 colors in Current Colors
But when I clicked on this colors, the full palette will show (I don't know about it :))

![](http://i.imgur.com/pkB4gdp.png)

So it's my mistake - sorry :)

> Project or file?

I will be test both ways in a few day and give you feedback.

Another bug? is - sometimes the color does't indexed.
I try to use the option: Color Helper: Index Colors in File, but they return:
error: Cannot index colors in this file!

**Comment by facelessuser** [comment]
> Another bug? is - sometimes the color does't indexed.
I try to use the option: Color Helper: Index Colors in File, but they return:
error: Cannot index colors in this file!

Maybe indexing is already occurring so it is busy at the time?  I guess without more info it is difficult for me to guess.  I will look at what I display for the message and change it to something more useful if that was the problem.  If that wasn't the problem, I will need more info before I can resolve it.

As the the original stated issue is apparently resolved, I will go ahead and close this issue.
