### ISSUE TITLE
not show current colors

### ISSUE THREAD

**Issue by ildarkhasanshin** [facelessuser/ColorHelper#31]
not show block current colors
only favorites, random colors, old clover, yet another
st3 3103
ubuntu 15.10

**Comment by facelessuser** [comment]
You are going to need to post your settings, and an example file (with colors in it), and also let me know what syntax package you are using to highlight your text.  If I am able to reproduce your problem, I'll let you know, but current colors work for me currently.

**Comment by ildarkhasanshin** [comment]
setting the default package
forgot to say that i have installed another package https://github.com/Monnoroch/ColorHighlighter

**Comment by facelessuser** [comment]
I am going to need you to provide what I asked for in my first response.  I am not concerned with other plugins at this moment.  I am currently looking to see if you have ColorHelper configured for your setup properly.

**Comment by ildarkhasanshin** [comment]
css
https://www.dropbox.com/s/1i2nw8cc8ye3g0a/template_styles.css?dl=0

console's exception
https://www.dropbox.com/s/8fuf21u0fhhivcn/st3_console.log?dl=0

**Comment by facelessuser** [comment]
I still need your ColorHelper personal settings (if you set any).  I also need to know what syntax highlighting package you are using to highlight your CSS file.  Are you using the default CSS package?

**Comment by ildarkhasanshin** [comment]
> I still need your ColorHelper personal settings (if you set any)
default settings, user's settings-file empty

> Are you using the default CSS package?
yes

**Comment by facelessuser** [comment]
Thanks, found the issue.

**Comment by ildarkhasanshin** [comment]
+
how update plugin?

**Comment by facelessuser** [comment]
It will update through Package Control when I make a release tomorrow.  Once I make the release, you will either have to wait for Package Control to update automatically, or run the `Package Control: Upgrade Package` command to force the upgrade sooner.

**Comment by ildarkhasanshin** [comment]
updated plugin, no changes - there were no current colors

**Comment by facelessuser** [comment]
Updated how?  I haven't released it yet.

**Comment by facelessuser** [comment]
It has now been released as 1.3.5, so as soon as it is available in Package Control, you can upgrade.

I have personally tested the fix, so I know it is working.

**Comment by ildarkhasanshin** [comment]
you do not believe it, but I have not changed
although ColorHelper.sublime-package this time really updated
current colors are not displayed
and the console displays the same
even folder ../Cache cleared

**Comment by facelessuser** [comment]
Using your exact css file that you gave me, using the default CSS syntax highlighter, using default settings, and using the latest ColorHelper, I cannot reproduce your issue.

Did you restart Sublime after upgrading? Are you now getting a different error?  Because if you really have the latest, you should not be getting the same error.  If you are getting the same error on the same line, then you can't have the latest.

Please provide any errors in the console.  Right now, I am thinking you either need to restart, or it hasn't really upgraded.

**Comment by facelessuser** [comment]
I just also ran the most recent ColorHelper on Ubuntu 15.04.  From my perspective, this issue is fixed unless you can provide me with some more info proving otherwise.

Check your console for new errors, try disabling other plugins etc.

**Comment by ildarkhasanshin** [comment]
current colors appear only if the part of file to clear (for testing)
later try to test on clean st3

**Comment by facelessuser** [comment]
> current colors appear only if the part of file to clear (for testing)
later try to test on clean st3

I am not sure what you mean here.  Once you have done some more testing, just provide any console errors (if any) and a a clear description of the problem.  Hopefully, you'll be able to get it working.
