### ISSUE TITLE
Show color in small square in gutter

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#32]

**Comment by aziz** [comment]
Gutter is already a crowded area and until we have APIs to add multiple symbols to the gutter I would vote down on this one.

**Comment by facelessuser** [comment]
I kind of agree with @aziz, and as I recall, there is already a plugin for that: https://packagecontrol.io/packages/Gutter%20Color.  ColorHelper is a different approach on purpose; I don't necessarily want to assimilate features of all color plugins.
