### ISSUE TITLE
Display color value in autocomplete

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#35]
It's possible to display color value in autocomplete list in this same way as is display in gutter? 

![](http://i.imgur.com/WM9ZBWm.png)

Final effect:

![](http://i.imgur.com/u1HzK71.png)

**Comment by facelessuser** [comment]
I guess I don't really understand what is being suggested.  You want the color preview of the auto complete value?

1. I don't think you can insert colors previews into an autocomplete box via the Sublime API.

2. In general ColorHelper is designed to give you info on a specific selected color, or to insert colors.  It does keep track of colors in a specific file for reuse in other places, but it doesn't have intelligence to associate a color with a specific variable in a specific file type.  ColorHelper currently doesn't care what file type it is in really (meaning it doesn't care about file syntax); it doesn't know that `$green` is a variable for a color, it just sees the color `#00b900` and only stores that information.  I purposely didn't want to hard code such logic to make it flexible for different types of files (not just SCSS, SASS, and/or CSS).

**Comment by facelessuser** [comment]
I'm going to close this as what you are requesting isn't possible.  I am thinking about using phantoms to display colors next to CSS colors, but that is a separate issue.
