### ISSUE TITLE
not clear instruction 

### ISSUE THREAD

**Issue by VitaliyAT** [facelessuser/ColorHelper#38]
I did what was written in installation (package installed), but have no popup or any windows that shown on https://facelessuser.github.io/ColorHelper/usage/#general-usage No reaction on triggers sych as # or rgb or any other from documentation. Misunderstanding, what's wrong? 
Also I see note: "Popups are provided by the mdpopups dependency." - Give me more misunderstanding: should I install it too? if true then how (no info about it in internet)?
Help me, please - I like ColorHelper a lot and want use it!

**Comment by facelessuser** [comment]
Did you install via Package Control?

Also what text were you trying the plugin out on, and what syntax highlighter were you using on that text (was it a built-in syntax highlighter or third party and what was it's name)?

**Comment by VitaliyAT** [comment]
I don't know how. look like after 3 restarts or maybe all computer reset it start to work. Can't give more details.

**Comment by facelessuser** [comment]
I don't know.  As long as it is now working for you, I guess that is all that matters.  If you ever have the issue again and can give me steps to reproduce, I'll take a look at it, but for now, I will close this.
