### ISSUE TITLE
On very first draw, topmost phantom is cut off

### ISSUE THREAD

**Issue by jcberquist** [facelessuser/ColorHelper#45]
This isn't a big deal at all, really it is just puzzling. When I first start Sublime Text, the very first time any inline phantom color blocks are rendered the topmost one gets cut off:
 ![image](https://cloud.githubusercontent.com/assets/3498220/17161918/4e95d5d6-537f-11e6-8c7e-656a7697e069.png)
It looks to me like it is the right size, it is just that its positioning is off. As far as I can tell it only happens then. Every other file thereafter, including the original one, renders all of the phantoms just fine.

**Comment by facelessuser** [comment]
Has this always been the case, or is this related to the recent ST dev version?  I was getting close to releasing another ColorHelper bug fix release, but this is not a bug I have seen or addressed.

**Comment by jcberquist** [comment]
Unfortunately, I can't tell you. I installed your package after the last update this morning. I am happy to try it on 3118 and see what happens...

**Comment by facelessuser** [comment]
Also please post info gathered by running the menu command `Preferences->Package Settings->ColorHelper->Support Info`.  Additionally, point me at syntax package you are using for CSS, font you are using, and anything else you have that could maybe help me replicate the issue.

To be honest, I don't see how ColorHelper would mess this up.  I have a function that generates all images exactly the same.  The code used to generate the images isn't the kind that would act differently depending on the iteration it is run at.  As you can see on my machine it looks fine:

![screenshot 2016-07-26 20 39 29](https://cloud.githubusercontent.com/assets/1055125/17162185/2a34640e-5371-11e6-9fa9-6ef91ae8194d.png)

I've got a suspicion that whatever is happening is specific to your installation.  If you are on windows, I wonder if you downloaded the portable version if you would see the issue in the fresh install.   Not sure if you are on OSX though as there is no portable version you could try.

**Comment by jcberquist** [comment]
So first, here is the info you requested:
```
- ST ver.:        3119
- Platform:       windows
- Arch:           x64
- Plugin ver.:    2.0.2
- Install via PC: True
- mdpopups ver.:  1.7.6
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8
```
However, I did download 3118 portable, copied my user folder in and got all my packages installed. The issue did not show up. I then let 3118 update to 3119, and the issue shows up there too now.

**Comment by jcberquist** [comment]
Additionally, this is my current settings file:
```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Monokai.tmTheme",
	"font_face": "Consolas",
	"font_options": ["directwrite"],
	"font_size": 10,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"overlay_scroll_bars": "enabled",
	"theme": "Boxy Monokai.sublime-theme",
	"theme_accent_blue": true,
	"theme_bar": true,
	"theme_bar_colored": true,
	"theme_bar_shadow_hidden": true,
	"theme_button_inverted": true,
	"theme_button_rounded": true,
	"theme_dropdown_materialized": true,
	"theme_find_panel_atomized": true,
	"theme_icon_button_highlighted": true,
	"theme_icons_atomized": true,
	"theme_panel_switcher_materialized": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_quick_panel_size_md": true,
	"theme_tab_close_always_visible": true,
	"theme_tab_line_size_lg": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
	"trim_trailing_white_space_on_save": true
}
```

**Comment by facelessuser** [comment]
> However, I did download 3118 portable, copied my user folder in and got all my packages installed. The issue did not show up. I then let 3118 update to 3119, and the issue shows up there too now.

You know what that sounds like...a Sublime 3119 bug.  Unfortunately, all I can do is tell give sublime the popup HTML and tell it where to stick it.  I can't really control how Sublime inserts it unless it is a formatting issue (like if I added too much padding etc.).

With that said, I'll try out some of your settings on my Windows box tomorrow and see if I can force the issue.  Even if I expose the magic combination, I'm not sure if it is something I can directly address in the plugin as it sounds like it may be a bug in Sublime itself.  Unless maybe it's a timing thing, like if you render a phantom too after Sublime starts up, it messes up the first phantom.  I guess we'll see first if I can force the bug on my machines, then we'll go from there.

**Comment by jcberquist** [comment]
Yeah, I think you are right. I am not sure what it is about my setup, but with only PC and ColorHelper on 3119 portable, and with no custom settings, it still happens for me.

**Comment by facelessuser** [comment]
I am seeing it in my other plugin ScopeHunter:

![screenshot 2016-07-26 21 09 26](https://cloud.githubusercontent.com/assets/1055125/17162697/6b1a0740-5375-11e6-8ad9-9db8702a5f34.png)

This is new.

**Comment by jcberquist** [comment]
Given the significance of the update to minihtml in 3119, I suppose it is not surprising that something like this might crop up. You are welcome to close this issue if you like, as this doesn't seem to be a problem with ColorHelper.

**Comment by facelessuser** [comment]
Will do.
