### ISSUE TITLE
[Feature] Add support for drawing phantom in front of color code

### ISSUE THREAD

**Issue by jcberquist** [facelessuser/ColorHelper#46]
I think it would be nice to have the option to have the inline color phantom drawn before the color code in addition to the current placement of afterwards. For example:
![image](https://cloud.githubusercontent.com/assets/3498220/17185295/84f3bb96-53fe-11e6-8810-9257da60b759.png)

**Comment by facelessuser** [comment]
I've actually debated about doing this as the default :smile:.  It is in the plan.  Maybe I'll get to it tonight.  Should be a trivial addition.

**Comment by facelessuser** [comment]
I went with this as the current way.  The reason is it simplifies some of the code as now the box is at the start of the color text region instead of 1 after.  Also, colors line up nice regardless of format (rgb vs hex etc.).  I'll see if people gripe, but I'll probably still leave it this way as I like it better.

**Comment by jcberquist** [comment]
Thanks! You won't get any complaints from me :smile:

**Comment by jcberquist** [comment]
Update looks great! Thanks again. And thanks for eliminating the flicker, too.

**Comment by keith-hall** [comment]
I personally preferred the phantom to the right of the color, but I wonder how I would have felt if I had only ever seen it on the left... i.e. maybe it's just me not liking change hehe ;)

**Comment by facelessuser** [comment]
> but I wonder how I would have felt if I had only ever seen it on the left.

I know.  It's why I kick myself every time I release something before I've settled on exactly what I want.  I'll take it into consideration though for the future.  If enough people request the other way, maybe I'll switch it back...or maybe I won't 😈 .

For now I'm probably going to leave it as is.
