### ISSUE TITLE
Keyboard Shortcut for Color Picker

### ISSUE THREAD

**Issue by enkia** [facelessuser/ColorHelper#47]
Apologies if this has already been addressed, but I couldn't find anything in issues.

I'd like to set `"auto_popup": false,` and use a keyboard shortcut to activate the color picker when caret is on a color. Is there a command to use for key mappings?

**Comment by facelessuser** [comment]
Just adapt this to your needs: https://github.com/facelessuser/ColorHelper/blob/master/Default.sublime-commands#L21.

**Comment by enkia** [comment]
Ahh, I should have figured that out. Thanks!
