### ISSUE TITLE
Outer Border

### ISSUE THREAD

**Issue by enkia** [facelessuser/ColorHelper#48]
What are your thoughts about possibly changing the outer border to `OUTER_BORDER = '#000000ff'`

It seems easier on the eyes?

![outer_border](https://cloud.githubusercontent.com/assets/255730/17274413/b071e3cc-56ad-11e6-9649-9c06a74db800.png)

_Edit:_ Then again, it may not, depending on the background of a user's color scheme.

**Comment by facelessuser** [comment]
I'm changing some things in mdpopups moving forward.  I'll will be modeling Sublime approach in the latest releases.  Popup backgrounds will be configured by themes or Sublime will autogen them.  As always, you will be able to tweak this in your custom mdpopups.css.

**Comment by enkia** [comment]
Looking forward to it!
