### ISSUE TITLE
Inline phantoms background color should be transparent

### ISSUE THREAD

**Issue by aziz** [facelessuser/ColorHelper#50]
You notice it when the area that the color box appear in has a different background color from the rest of view.
<img width="326" alt="screen shot 2016-08-04 at 3 32 03 am" src="https://cloud.githubusercontent.com/assets/3202/17387475/6f038180-59f4-11e6-9d3c-677a1d74ce9f.png">

**Comment by facelessuser** [comment]
If you could post ColorHelpers support info, it would help.

Keep in mind I strip out all padding, and margins (especially in phantoms) and generate the images all the way to the edge.  So a couple of things are happening here either:

1.  Your color scheme is adding some margin or padding (depends on CSS combinations of mdpopups and your theme).

2. Sublime is being silly.  If you are windows, this is very likely.  Builds 3119 - 3120 on all my Windows systems are shrinking images and distorting them.  This is a bug in Sublime, so if that is the case, it is out of my control.

**Comment by facelessuser** [comment]
References:

- CSS of mdpopups - https://github.com/facelessuser/sublime-markdown-popups/blob/master/css/base.css#L11

- Sublime issue: https://github.com/SublimeTextIssues/Core/issues/1308

- Forum examples: https://forum.sublimetext.com/t/colorhelper-2-0-0/21762/61

**Comment by aziz** [comment]
- ST ver.:        3120
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.0.5
- Install via PC: True
- mdpopups ver.:  1.9.1
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8

**Comment by aziz** [comment]
@facelessuser It's not like that, I changed the font and took a new screenshot to show the problem better. It's a markdown document with a bluish background. It's using a custom markdown syntax that parses markdown fenced code and highlight them with appripriate language and set a darker background color for that section. but the phantom still has the bluish background. 

<img width="407" alt="screen shot 2016-08-04 at 4 26 26 am" src="https://cloud.githubusercontent.com/assets/3202/17388369/fa815b86-59fb-11e6-8f24-d33865f6f1a2.png">

**Comment by aziz** [comment]
Can't you set the background color of the html to transparent for phantoms? 
Something like ` html { background-color: transparent; }` should suffice.

**Comment by facelessuser** [comment]
What the...
Can you send me said color schemes and such?

**Comment by facelessuser** [comment]
Nv.  I see it is your notes plugin you are using.  Let me test it out.

**Comment by aziz** [comment]
It's my `PlainNotes` plugin. install it using package control and then:

- open a new tab
- set syntax to `Note`
- run command `Note: change color`
- select one of the colors, in this case it's the light blue. 
- paste the below sample code:

```
# This is a markdown document

the color scheme is bluish

\`\`\`css
html {
  background-color: #00161B;
  font-family: "consolas";
  color: #F8F8F8;
  padding: 0;
}
body {
  background-color: #00161B;
  font-family: "consolas";
  padding: 0.2em;
}
\`\`\`
```

**Comment by aziz** [comment]
The gist of what I'm saying is that you can NOT trust the color scheme background color and set it as the background color of the phantom. I guess, mdpopups does this now and is fine for popups but not for inline phantoms. phantoms should be transparent

**Comment by facelessuser** [comment]
It may not be as simple as you think.  The image should extend to the edge of the HTML.  Even if you do offsets make the image smaller, no padding is getting added.  What if you are seeing how Sublime handles HTML that is smaller than the line?

**Comment by aziz** [comment]
You're right, it's Sublime's fault. I just created a small phantom with below HTML and I still see the bluish background.

<img width="98" alt="screen shot 2016-08-04 at 4 51 43 am" src="https://cloud.githubusercontent.com/assets/3202/17388853/309371ac-59ff-11e6-91b3-84fec529e4f1.png">


```html
<style>
  html {
    margin: 0;
    padding: 0;
    background-color: transparent;
  }

  body {
    margin: 0;
    padding: 0;
    background-color: transparent;
  }
</style>
<img width="16" height="16" src="res://Packages/sandbox/html/images/folder_yellow.png" />
```

I guess we found another Bug!

**Comment by facelessuser** [comment]
I was just about to post the results showing the same thing 😄 .

**Comment by facelessuser** [comment]
> I guess, mdpopups does this now and is fine for popups but not for inline phantoms. phantoms should be transparent.

If they ever make transparent HTML backgrounds work like we would expect, I think people could add that in their `User/mdpopups.css`.  I am actually backing away from defining colors unless I have to moving forward.  I plan on letting themes and Sublime provide basic colors since now that is an option.  I will stick to basic formatting and only colorize things I have to like `hr` tags, or inline `code` or `pre` tag backgrounds.
