### ISSUE TITLE
Incorrectly highlighting web colors in variables [SCSS]

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#51]
When I have variable (in SCSS) with dash in name - the position of square with the color is wrong:
![](http://image.prntscr.com/image/cd3c2cbeb7194c4a945671091bcb2f13.png)

**Comment by facelessuser** [comment]
It's not supposed to highlight variables.  So it isn't wrong position, it just highlighted `green` incorrectly.  When filing issues like this, please always provide syntax file being used and best example.  Also, pictures are fine, but always place plain text examples I can copy and paste as well.

**Comment by PixelT** [comment]
I used: https://packagecontrol.io/packages/SCSS

**Comment by facelessuser** [comment]
I figured out the issue.  I just had a typo that incorrectly defined the lookbehind that was supposed to keep this from happening.
