### ISSUE TITLE
No picker showed on latest macOS 10.12 developer version

### ISSUE THREAD

**Issue by syhily** [facelessuser/ColorHelper#52]
<img width="917" alt="2016-08-04 23 03 48" src="https://cloud.githubusercontent.com/assets/1761698/17406863/c4e924b2-5a97-11e6-9530-4308acbec891.png">

```
CONVERT CALL:
convert -type TrueColorMatte -channel RGBA -size 32x32 -alpha transparent xc:none -fill "#00BCD4FF" -draw "circle 15,16 8,10" png32:"/Users/Yufan/Library/Application Support/Sublime Text 3/Packages/User/Color Highlighter/icons/00BCD4FF.png"
convert error:
/bin/sh: convert: command not found
```

**Comment by facelessuser** [comment]
Works for me.  Did you restart after update?  Also post the info from `Preferences->Package Settings->ColorHelper->Support Info`.

**Comment by syhily** [comment]
```
- ST ver.:        3120
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.1.0
- Install via PC: True
- mdpopups ver.:  1.9.3
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8
```

No error showed after brew install imagemagick, but the picker didn't work either.

**Comment by facelessuser** [comment]
`imagemagick` should have nothing to do with it.  I don't use `imagemagick`.

This isn't from my plugin. 
```
CONVERT CALL:
convert -type TrueColorMatte -channel RGBA -size 32x32 -alpha transparent xc:none -fill "#00BCD4FF" -draw "circle 15,16 8,10" png32:"/Users/Yufan/Library/Application Support/Sublime Text 3/Packages/User/Color Highlighter/icons/00BCD4FF.png"
convert error:
/bin/sh: convert: command not found
```

See it says `Color Highlighter.  This plugin is `ColorHelper`.

Did you restart?

**Comment by syhily** [comment]
Yeah, totally restart

**Comment by facelessuser** [comment]
Hmm.  Try to delete `mdpoups` from your `User` folder, then try run `Satisfy Dependencies` from the command palette.  After Package Control finishes up in the console, try and restart ST.  I actually do my main development for these on OSX, so I test on OSX more so than any other system.

**Comment by facelessuser** [comment]
The reason I think something is wrong with mdpopups is that I added a feature to turn off newline to br tags in the rendering, but your popup shows it turning newlines into br tags.

**Comment by syhily** [comment]
Sorry, this didn't work either.

**Comment by facelessuser** [comment]
I would say uninstall ColorHelper and reinstall.  Whatever the issue is, it looks specific to your machine, not the plugin as I have tried this on OSX, Windows, **and** Linus and they all work.  It seems like something is corrupt on your machine.

As a last ditch effort, you can always try this: https://www.sublimetext.com/docs/3/revert.html.

**Comment by syhily** [comment]
<img width="798" alt="2016-08-04 23 57 44" src="https://cloud.githubusercontent.com/assets/1761698/17408871/72be54d4-5a9f-11e6-906d-c6836d745d2a.png">

Yeah, it works after reset sublime text. Tks for your help anyway.

**Comment by syhily** [comment]
This plugin couldn't work well with [Material Theme](https://github.com/equinusocio/material-theme). Could you please fix this?

**Comment by facelessuser** [comment]
Me?  Isn't that a Material Theme thing?

The author is setting links to `display: block`.  They should not do that.  That is an issue on their side.
https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme-Darker.tmTheme#L39

**Comment by syhily** [comment]
Got it, but I don't know how to express this issue clearly. Could you please submit an issue on their repository? Tks.

**Comment by facelessuser** [comment]
> Could you please submit an issue on their repository?

Just did, you can see the issue is now linked to this one.
