### ISSUE TITLE
Can't get higher than 3114

### ISSUE THREAD

**Issue by katerlouis** [facelessuser/ColorHelper#53]
Sorry if this issue may be on the wrong repo :X

I'm on Build 3114 and there are no updates.
Google says 3118 is a dev version.
Is there any way I can update to 3118 without rebuilding my whole setup?

**Comment by facelessuser** [comment]
1. You have to have a valid license.
2. You just install the 3118+ version over top your old version. https://www.sublimetext.com/3dev

For the most part, everything will work as expected.  Keep in mind you will then be on the bleeding edge, so use caution on when to accept updates.  But usually you can always roll back to a good version by modifying the download link with a past unlisted version.  3119-3120 is pretty good , but on Windows, it has some image distortion issues in popups and phantoms.  You have to either ignore it for now, or use 3118; I've just been ignoring them.

**Comment by katerlouis** [comment]
Thanks for the quick reply!

I have a valid license;
I'm curious what fancy feature color highlighter is using that it only works in a future update :D

That being said, can you estimate the time until your plugin will work in stable releases?

**Comment by facelessuser** [comment]
Currently it will still work on 3114.  The current requirement is that it's dependency (mdpopups) gets updated to the latest, not Sublime.  Mdpopups is a library I use for any of my plugins that deal with popups or phantoms.  I don't want to keep putting in feature switches every time I update mdpopups to do something I want to take advantage of, so sometimes I just draw a line and say you need this version so I can clean up old feature switches.

Anyways, new Sublime versions have phantoms.  I don't know if you looked at the repos front page and saw the gif, but inline color previews (color preview right next to the text form of your color) have been added.

**Comment by facelessuser** [comment]
I think this has been answered, so I will go ahead and close this.

**Comment by katerlouis** [comment]
Sorry, long time no answer–
I'm confused; so you say I could run it with 3114 if I update "MDPopups"? Where do I get these MDPopups from? :>

Please excuse my newbieism.

**Comment by facelessuser** [comment]
What I am saying is that Color Helper will work on 3114.  Its required dependency `mdpopups` should be updated to the latest to keep it working, though this doesn't mean you will get all the latest features as that is partly dependent on what Sublime version you are on as well.  But currently, it is best to have the latest.

- Package Control should update Color Helper without you having to do anything
- Package Control **should** update the `mdpopups` dependency on update of Color Helper, but doesn't always.  To manually do this, run the Package Control command `Satisfy Dependencies` from the command palette, and then restart Sublime.  **If** this doesn't work for some reason, as a last resort, you can delete `mdpopups` manually, run `Satisfy Dependencies`, and then restart Sublime.
- Sublime should inform you of upgrades, but you can always install the latest by downloading and installing over the old.  There are two branches, the beta branch and the dev branch.  You can download from either, but you must have a valid license to use the dev branch.

If you need to see what versions you have, you can select the command from `Preferences->Package Settings->Color Helper->Support Info`.  This should tell you what versions you have.

These are the latest versions as of today:

- ST ver.:        3120
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.1.1
- Install via PC: False
- mdpopups ver.:  1.10.0
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8

Hopefully I've covered everything.

**Comment by katerlouis** [comment]
Now that I have 3126 colorHelper still isn't working.
I removed and reinstalled through package control.

Nothing happened with my file. Restarting sublime text didn't help either.
When I run the command in command palette `Color Helper: Index Colors in file` I simply get an error, both as a modal and in console:
`error: Cannot index colors in this file!`

What is happening? :(

**Comment by facelessuser** [comment]
I don't know, I would post versions for ColorHelper as I post above, I would provide info on the file type you are evaluating, I would post what syntax highlighter you are using (specifically what package: default, 3rd party with name, etc.).  Are there errors in your console?

There are an infinite number of reasons why it may not be working, and sadly my psychic debug skills aren't that great :wink:.  The more info you can provide, the better chance I am able to pinpoint the issue.  Maybe some other package is interfering, maybe you need a clean install of Sublime, maybe something is incorrect in your settings files, maybe your install of ColorHelper is corrupt, maybe something else.

What I can say is that it is working for me on the most recent ST build, and it is generally working for others as well.  This seems to be an isolated case with your machine, and without further info, I can only guess.

**Comment by katerlouis** [comment]
Silly me– sorry for that. Usually not my style. Frustration must've got to me..

– regarding to PackageControl subheadline I just installed ColorHelper 2.1.1
– I use the LESS Syntax provided by the LESS package (https://packagecontrol.io/packages/LESS)
– Color Helper Show palettes, Show Info and Color Picker, add & mark are working fine as far as I can tell.
– I had "Color Highlighter" and "Color Picker" packages installed aswell, but ignored. Removed them and reinstalled "Color Helper", still no highlighting in the code. Same error.

Here is the console:

```
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["AutoFileName", "BufferScroll", "CodeKit Commands", "Color Highlighter", "ColorPicker", "Material Theme - Appbar", "Material Theme - White Panels"]
reloading plugin ColorHelper.changes
reloading plugin ColorHelper.color_helper
reloading settings Packages/ColorHelper/color_helper.sublime-settings
reloading plugin ColorHelper.color_helper_insert
reloading plugin ColorHelper.color_helper_picker
reloading plugin ColorHelper.color_helper_util
reloading plugin ColorHelper.multiconf
reloading plugin ColorHelper.support
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "color_helper in /Users/reneeschke/Library/Application Support/Sublime Text 3/Installed Packages/ColorHelper.sublime-package", line 1451, in <lambda>
  File "color_helper in /Users/reneeschke/Library/Application Support/Sublime Text 3/Installed Packages/ColorHelper.sublime-package", line 1502, in on_view_settings_change
AttributeError: 'NoneType' object has no attribute 'path'
/Users/reneeschke/Library/Application Support/Sublime Text 3
LOADING BOOKMARKS
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "color_helper in /Users/reneeschke/Library/Application Support/Sublime Text 3/Installed Packages/ColorHelper.sublime-package", line 1451, in <lambda>
  File "color_helper in /Users/reneeschke/Library/Application Support/Sublime Text 3/Installed Packages/ColorHelper.sublime-package", line 1502, in on_view_settings_change
AttributeError: 'NoneType' object has no attribute 'path'
reloading /Users/reneeschke/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
```

**Comment by facelessuser** [comment]
I want you to follow my steps for posting all version info.  I need the version of all moving parts.

> If you need to see what versions you have, you can select the command from Preferences->Package Settings->Color Helper->Support Info. This should tell you what versions you have.

Also post some example code that you are trying this in.  Simpler the case the better.

**Comment by katerlouis** [comment]
Sweet feature:
```
- ST ver.:        3126
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.1.1
- Install via PC: True
- mdpopups ver.:  1.10.0
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8
```

Code example: `vars.less` (exactly first 19 lines)
```less
/**
 *
 * Vars
 *
 */

/*=================================
=            Variablen            =
=================================*/


@min-width: 305px;
@max-width: 1600px;

@color: #000;

@color_kids: red;
@color_school: #5a9cc5;
@color_fitness: yellow;
```

**Comment by facelessuser** [comment]
I will take a look when I get a chance.
