### ISSUE TITLE
Setting up colorhelper for CSS3 syntax

### ISSUE THREAD

**Issue by reesebiz** [facelessuser/ColorHelper#54]
I recently installed the the [CSS3 package](https://packagecontrol.io/packages/CSS3) and was wondering how do I set up ColorHelper to work with it? Not just for CSS3, but for any syntax really. How is that set up? I tried messing with the `color_scanning` shown in the documentation but i'm not sure if that's the correct method.

**Comment by facelessuser** [comment]
Just committed the change.  You should see it linked to this issue.  I will try to get a release out before I go on vacation.

**Comment by facelessuser** [comment]
It's been released, so whenever Package Control officially sees it, you should get it.

**Comment by reesebiz** [comment]
This worked great, thank you!
