### ISSUE TITLE
System color picker integration

### ISSUE THREAD

**Issue by equinusocio** [facelessuser/ColorHelper#55]
It would be awesome if the picker functionality can use the system color picker if exist. Like ColorPicker plugin, when we click on the color preview (inside the popup) the color picker window (OS X) should be used. It works more efficiently and allow to pick color from everywhere on the screen. Maybe ColorHelper can use ColorPicker is installed or, if on OS X, use the native one, otherwise it should use the current one.

All of this can be handled by a package setting like `use_system_color_picker`.

**Comment by aziz** [comment]
It's already implemented. see the settings file

**Comment by facelessuser** [comment]
Thanks @aziz  for answering this.

**Comment by adaringdesign** [comment]
How do I enable this, I can't get the OS X picker to open? Can someone clear this up?
