### ISSUE TITLE
add support for short hex

### ISSUE THREAD

**Issue by ctf0** [facelessuser/ColorHelper#56]
something like `#fff`

**Comment by facelessuser** [comment]
This is already supported.

**Comment by facelessuser** [comment]
![screenshot 2016-08-31 22 00 15](https://cloud.githubusercontent.com/assets/1055125/18154979/62b8e87e-6fc6-11e6-9d97-527febebf093.png)

**Comment by ctf0** [comment]
for some reason it wasn't working weird , now i only have issue with `stTheme`

```json
{
    "syntax_files": [],
    "syntax_filter": "whitelist",
    "base_scopes": ["text.xml"],
    "scan_scopes": ["text.xml -meta.tag.xml -comment -string"],
    "allowed_colors": ["hex", "hexa"],
    "extensions": [".tmTheme", ".stTheme"],
    "use_hex_argb": false,
    "compress_hex_output": false
}
```
![test](https://cloud.githubusercontent.com/assets/7388088/18155213/bd56ee08-700b-11e6-8cc2-b706e6e64f51.jpg)

**Comment by facelessuser** [comment]
Compressed hex output is set to false in your settings.

**Comment by ctf0** [comment]
thanx, also `"allowed_colors": ["hex", "hexa", "css3"],` needs to be changed , i can make a PR with those changes if u want

**Comment by facelessuser** [comment]
Why did you add CSS3?  tmTheme should only have hex values.  I think a pull with the compressed makes sense, but I'm not sure about the CSS3.

**Comment by ctf0** [comment]
because without the `css3` some hex wont work , it was just a try and error option

**Comment by facelessuser** [comment]
Can you give examples?  I'd like to understand the real issue.

**Comment by ctf0** [comment]
sure, with & without css3, the shortcode doesn work without the css3

![test](https://cloud.githubusercontent.com/assets/7388088/18155692/4d729916-7010-11e6-9e44-bb32ce5f5557.jpg)

**Comment by facelessuser** [comment]
Sorry, I know what the issue is.  `compress_hex_output` will compress the inserted hex output; it doesn't control what is recognized.  Instead of `CSS3` and `hex_compressed`.  That should give you what you want.

**Comment by ctf0** [comment]
sweet, all good now, thanx again
