### ISSUE TITLE
Duplication of color previews

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/ColorHelper#57]
Colors on occasions start getting doubled.  For some reason, ColorHelper is no longer aware of the existing phantoms. https://forum.sublimetext.com/t/colorhelper-2-0-0/21762/82.

Need to figure a way to force it into this state reliably and collect enough data to come up with a solution.

**Comment by aziz** [comment]
I've also noticed this bug numerous times.

**Comment by facelessuser** [comment]
Anyone who can help find a way to reproduce it reliably will greatly help in this getting resolved.  Most of the time when I am trying to reproduce it I can't.  On rare occasions that I don't have time to debug it, that is usually when I see it 😦 .

**Comment by facelessuser** [comment]
In the next release, if this isn't actually fixed, please let me know.  I think this should fix the issue.
