### ISSUE TITLE
extend support to something like "layer1.tint": [138,157,166],

### ISSUE THREAD

**Issue by ctf0** [facelessuser/ColorHelper#58]
in sublime-theme files

**Comment by facelessuser** [comment]
I probably won't implement this directly, but I plan to redesign things as mentioned in #42 and expose the knobs and such.  That way I don't have to manually add color support in every file type people come up with.  In the future I imagine color support added via pull requests by 3rd parties than me implementing it directly.  Not sure when the redesign will be done, but when I get time and complete this, it should be possible.

**Comment by ctf0** [comment]
maybe this could be solved via some smart regex ? , something like htmlbeautify

**Comment by facelessuser** [comment]
There are a lot of things to consider that are specific to the color format.  It will be quite a bit more than just adding regex.  There are quite a bit of hooks that need to be added.

**Comment by ctf0** [comment]
oooooh , okay then, thanx again
