### ISSUE TITLE
The color blocks are duplicating some time I save my syntax file

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/ColorHelper#62]
### The color blocks are duplicating some time I save my syntax file

You may get the same color theme on: https://github.com/evandrocoan/SublimeNotepadPlusPlusTheme
Sublime Text 3, build 3126 x86 windows 10

![image](https://cloud.githubusercontent.com/assets/5332158/18812123/d340ac76-829f-11e6-985e-174b9cfb2e09.png)

**Comment by facelessuser** [comment]
Please do check existing issues before opening a new one. This is a duplicate issue of #57.

**Comment by evandrocoan** [comment]
I checked their titles and doubling color tags was not very intuitive at the moment.

**Comment by facelessuser** [comment]
¯\_(ツ)_/¯ we do what we can.
