### ISSUE TITLE
Converting to web_color gives invalid color like #ffff

### ISSUE THREAD

**Issue by DenVdmj** [facelessuser/ColorHelper#63]
When I convert to web_color from root menu (info.html) I get invalid color like „#ffff“:

![f1](https://cloud.githubusercontent.com/assets/988641/19286704/5666cea4-9007-11e6-9343-bd9835de488e.png)

Next, I choose „white“:

![f2](https://cloud.githubusercontent.com/assets/988641/19286708/57dbe008-9007-11e6-8a15-16200df56ce1.png)

I guess that this code („color_helper_insert.py“, line 42):

        if convert == "name":
            try:
                if len(target_color) > 7:
                    target_color = target_color[:-2]
                self.web_color = csscolors.hex2name(target_color)
            except:
                pass
            self.force_alpha = True

can be replaced by the following code:

        if convert == "name":
                self.web_color = csscolors.hex2name(target_color)

**Comment by facelessuser** [comment]
Yes at some point a bug was introduced, but the solution is actually to set `self.force_alpha` to `False`.  We don't want to remove the alpha stripping.

**Comment by DenVdmj** [comment]
> We don't want to remove the alpha stripping.
Ok. And what web color name rgba(0,0,0,.5)? Black80?

**Comment by facelessuser** [comment]
?  I think you are misunderstanding what the code is doing.  When I pass around a color, I pass it around with the alpha.  When we output the color name, we no longer need the alpha, so we strip it out.

**Comment by DenVdmj** [comment]
Hmm.. Sorry, you're right :)
