### ISSUE TITLE
Add support for https://packagecontrol.io/packages/Sass

### ISSUE THREAD

**Issue by PixelT** [facelessuser/ColorHelper#68]
### Description
The inline previews at this moment is visible only if the color is in hex value.
Maybe should be visible also in rgb, rgba, hsl, hsla values?

---

### Support Info
```
- ST ver.: 3125
- Platform: windows
- Arch: x64
- Plugin ver.: 2.2.0
- Install via PC: True
- mdpopups ver.: 1.11.0
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

### Steps to Reproduce Issue

Write in scss file:

```
$a: red;
$b: #fff;
$c: rgb(255, 255, 255);
$d: rgba(255, 255, 255, 1);
$e: hsl(0, 0%, 100%);
$f: hsla(0, 0%, 100%, 1);
```
![](http://i.imgur.com/s70xYiH.png)

```
a {
    text-decoration: none;
    background-color: red;
    background-color: #fff;
    background-color: rgb(255, 255, 255);
    background-color: rgba(255, 255, 255, 1);
    background-color: hsl(0, 0%, 100%);
    background-color: hsla(0, 0%, 100%, 1);
}
```
![](http://i.imgur.com/IFI5R9J.png)

The preview for rgb(a) and hsl(a) doesn't work with variables in scss

**Comment by facelessuser** [comment]
ColorHelper has recently implemented an issue template.  Support requires that the template be followed in order to get support.

But inline **is** supported for rgb, rgba, hsl, and hsla:

![screenshot - 11_8_2016 1_41_55 pm](https://cloud.githubusercontent.com/assets/1055125/20116362/306c900e-a5b9-11e6-9748-1ad50f92aeda.png)

If you require further assistance, please update the opening post using the template, and in detail describe your issue and provide everything the template asks.

**Comment by PixelT** [comment]
Write in scss file:

```
$a: red;
$b: #fff;
$c: rgb(255, 255, 255);
$d: rgba(255, 255, 255, 1);
$e: hsl(0, 0%, 100%);
$f: hsla(0, 0%, 100%, 1);
```
![](http://i.imgur.com/s70xYiH.png)

```
a {
    text-decoration: none;
    background-color: red;
    background-color: #fff;
    background-color: rgb(255, 255, 255);
    background-color: rgba(255, 255, 255, 1);
    background-color: hsl(0, 0%, 100%);
    background-color: hsla(0, 0%, 100%, 1);
}
```
![](http://i.imgur.com/IFI5R9J.png)

**Comment by facelessuser** [comment]
I've updated the opening post.  That is what I am looking for in the future.

You also need to tell me what syntax highlighter you are using in this example (provide the link to it please).

**Comment by PixelT** [comment]
For scss I'm using this package:
https://packagecontrol.io/packages/Sass

**Comment by facelessuser** [comment]
Most likely the scopes aren't including them.  I will take a look.

**Comment by facelessuser** [comment]
Fix will be in the next release.  I tested only very basic things as I don't use Sass.  So when it releases, you will have to test it to see if it behaves well.
