### ISSUE TITLE
hsl and hsla conversion broken

### ISSUE THREAD

**Issue by rgidney** [facelessuser/ColorHelper#7]
After updating to the latest version I noted that hsl and hsla no longer opened the tooltip and was getting conversion errors in the console. Looking at your updates to color_helper.py it seems you left off the .rstrip('%') when adding the decode. I added it back and it all works fine for me now.

Thanks,
Bruce

**Comment by facelessuser** [comment]
I'll have a fix in a minute. Thanks!

**Comment by facelessuser** [comment]
Fix is here https://github.com/facelessuser/ColorHelper/commit/f6b2629b5ca14f04eb472fa951d80ddb2ac3f197.

**Comment by rgidney** [comment]
Thank you :-)
