### ISSUE TITLE
Add option to remove white border on the color preview

### ISSUE THREAD

**Issue by jrvieira** [facelessuser/ColorHelper#71]
## Description

Preview is cluttered by border, especially when using colours similar to the background or the color picker. It could be easier to assess the colours if the border was less obtrusive (more transparent or replaced by a shadow…)

![screen shot 2016-12-02 at 02 42 32](https://cloud.githubusercontent.com/assets/16804617/20821265/0ce554da-b839-11e6-9ffc-e89e0e0d091f.png)

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.3.0
- Install via PC: True
- mdpopups ver.: 1.13.0
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

Use very contrasting or very similar colours to the background.

**Comment by facelessuser** [comment]
Thank you for your contribution to ColorHelper.  Unfortunately ColorHelper now requires all issues to follow the [issue template](https://github.com/facelessuser/BracketHighlighter/blob/master/.github/ISSUE_TEMPLATE.md). 
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Once the opening post has been updated, I will be happy to respond to this issue 😄 .

Please provide justification for your feature request as well.

**Comment by facelessuser** [comment]
Next time please provide all requested items in the template (including support info).  Issues that don't provide the suport info will be closed in the future.  Knowing the version of the plugin and plugin dependencies can be important for me when responding to bugs and even feature requests.

I do not believe the preview is cluttered by the border.  Without the border, color previews can blend into the background making it difficult for some to tell there is a preview.  A preview of the same color as the background could be mistaken for white space as well.  The border has been reduced down to a 1px border.  I can't make it smaller than that.

**Comment by jrvieira** [comment]
I understand. Apologies for misinterpreting the issue template format.

**Comment by facelessuser** [comment]
> I understand. Apologies for misinterpreting the issue template format.

No problem, thanks for understanding :).

The only other thing I could think of is I could make the border more subtle?  Maybe read the point where the insertion is meant to be inserted and calculate a border that is slightly lighter and darker than that points background?  Just an idea.

**Comment by jrvieira** [comment]
The problem I find is of colour perception, caused by the intense brightness of the border dividing a vast irrelevant space from such a small relevant space. From a graphic design and [visual psychology](https://en.wikipedia.org/wiki/Gestalt_psychology) standpoint I see two immediate things one could do to improve it.

One is exactly what you say, making the border less intrusive by blending it in with the background.

The other one is making the shape a circle instead of a square. This would allow your eye to better perceive the color by fixing the stare to the center — which we naturally do with circles — where the perceived color is more consistent (we tend to perceive the corners of the square as darker than the center because of the surrounding white pixels).

I think this may seem to tiny of a thing to spend a lot of time on because of the insignificant amount of time in which these phenomena occur, but I believe it's worth it because of the big improvement in usability it can prove itself to be and because I think this is exactly the point of your plugin. 

I understand that this is all very subtle and would like to hear your opinion on it.

**Comment by facelessuser** [comment]
> The other one is making the shape a circle instead of a square. This would allow your eye to better perceive the color by fixing the stare to the center — which we naturally do with circles — where the perceived color is more consistent (we tend to perceive the corners of the square as darker than the center because of the surrounding white pixels).

The only reason why I would currently shy away from this is because circles would require a more complex algorithm for me to generate.  Currently I am using a library where I literally generate the pictures pixel by pixel https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/colorbox.py.  Creating a good looking circle would require a bit of blending etc, and something I plan to avoid at the present unless things get to the point where I can generate the previews, with transparency, with CSS (which isn't currently possible with the phantom/popup framework) , or stumble upon a fairly portable and easy to use library that makes generating the circles simple.

So I think instead, I would opt for a simple, less intrusive border by blending it with the background.

**Comment by jrvieira** [comment]
Looking forward to see the result, hope it works. Thank you for a great plugin.

**Comment by facelessuser** [comment]
![screenshot 2016-12-02 18 54 56](https://cloud.githubusercontent.com/assets/1055125/20855925/56e887e0-b8c1-11e6-8db3-a371d865d6a3.png)
![screenshot 2016-12-02 18 56 07](https://cloud.githubusercontent.com/assets/1055125/20855928/59db7d68-b8c1-11e6-8a9a-13cd855d3c43.png)

How's that look?

This will only be applied in previews.  Unfortunately it is trickier when dealing with panels as a theme's popupCss can give me unexpected background colors, so I just go with a generic color that should work for a light theme or a dark theme to be safe.

**Comment by facelessuser** [comment]
I can maybe play around and try and reduce panel borders to 1 as I am using a double border currently.

**Comment by facelessuser** [comment]
We will leave the panel as is for now.  But the specified issue is resolved.

**Comment by jrvieira** [comment]
That's great man. Glad to contribute.
