### ISSUE TITLE
Popup is not appearing

### ISSUE THREAD

**Issue by megema** [facelessuser/ColorHelper#72]
## Description

After inserting a newline character, clicking on currently visible color previews (after the newline) does not toggle the popup anymore, only clicking on the text. Deleting the newline fixes the issue. Color previews generated by scrolling down are not affected. Tested in HTML and CSS files.

## Support Info

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.3.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open any supported file
2. Insert newline character
3. Try clicking on color previews after the newline

![dec -12-2016 18-31-34](https://cloud.githubusercontent.com/assets/19304551/21109411/3fd5ced4-c099-11e6-89ba-c93dc9ef45cf.gif)

**Comment by facelessuser** [comment]
Confirmed.

**Comment by facelessuser** [comment]
Thanks for the report.  I'll take a look this week.

**Comment by facelessuser** [comment]
This is now fixed on the main branch and will be available in the next version.
