### ISSUE TITLE
ColorHelper uses lowercase letters

### ISSUE THREAD

**Issue by emkei-cz** [facelessuser/ColorHelper#74]
Hello all,

Even though I have set big letters on the "true" ColorHelper still uses lowercase letters...
```
 // Upper case hex when inserting
 "upper_case_hex": true,
```

https://ctrlv.cz/shots/2016/12/14/3fyA.png

**Comment by facelessuser** [comment]
Thank you for your contribution to ColorHelper.  Unfortunately ColorHelper now requires all issues to follow the [issue template](https://github.com/facelessuser/ColorHelper/blob/master/.github/ISSUE_TEMPLATE.md). 
Please read and fill out this template by replacing the instructions with appropriate information.  If the template is not followed, the issue will be marked `Invalid` and closed.

Once the opening post has been updated, I will be happy to help you with this issue 😄 .

**Comment by emkei-cz** [comment]
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.3.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8


OK?

**Comment by facelessuser** [comment]
Can you elaborate on the issue?  I see the image of the colorpicker. Is the problem specific to the colorpicker only?  Or does the problem manifest in all insertions (even outside the colorpicker)?

**Comment by emkei-cz** [comment]
My English is not good sorry...

https://ctrlv.cz/shots/2016/12/14/NcMG.png

I want to use big letters when changing colors.

**Comment by facelessuser** [comment]
I'll take a look when I get a chance.

**Comment by emkei-cz** [comment]
> I'll take a look when I get a chance.

What?

**Comment by facelessuser** [comment]
It means I will fix it when I can.

**Comment by emkei-cz** [comment]
OK,

```
` // Upper case hex when inserting
 "upper_case_hex": true`
```
This setting does not work or something else entirely?

**Comment by facelessuser** [comment]
I haven't looked.  It is possible that it just doesn't work with the the color picker.  I probably need to make that information available to the color picker.

**Comment by emkei-cz** [comment]
thx,

and it will be added in the new version?

**Comment by facelessuser** [comment]
Yes, a new version.  Most likely the next.
