### ISSUE TITLE
Color Helper new version?

### ISSUE THREAD

**Issue by pavel-soukup** [facelessuser/ColorHelper#75]
Hi,

I see it on github source code ColorHelper updates.
But on https://packagecontrol.io/packages/ColorHelper see status:
"Version 2.3.0" and "Modified 3 weeks ago"

When will download a new version ColorHelper?

**Comment by facelessuser** [comment]
I don't know. I'm a busy man. I don't see three weeks as a cause for concern.  Currently I have at least one more issue I want to look at before I do.  Assuming I don't get side tracked on issues from my other repos, I imagine before the end of this month, but things happen.
