### ISSUE TITLE
Use 'edit_settings' to ... edit the settings

### ISSUE THREAD

**Issue by math2001** [facelessuser/ColorHelper#77]
---

## use `edit_settings` command

Since your plugin is only available on ST3, could you use the `edit_settings` command? It's much more efficient than having to open `settings - default` and then `settings - user` to compare each time I want to try something.

## Environment 

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.3.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

BTW, thanks for your plugin! I really enjoy using the converter and the preview's really cool!

Matt

**Comment by facelessuser** [comment]
I've been aware of this new API method for opening settings.  I have, so far, avoided it as I am not sure yet that I like it...but with that said, I may add it anyways.  As I recall, early betas of 3 did **not** support this, but I think most people are on a late enough version by now.

**Comment by facelessuser** [comment]
This will be in the next version
