### ISSUE TITLE
External project scan process

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/ColorHelper#8]
Project scanning should be done in an external process.
- For OSX and LInux, the plan is to write a python 3 and 2 compatible script that can scan a project.  It will create/modify a cache file and return.
- For windows, the aforementioned script will be compiled as an executable with PyInstaller.
- ColorHelper will spawn the process and monitor it in a thread.  The thread should be very light weight and not affect performance at all.
- When the process finishes, ColorHelper will then read in the cache and populate the project's special palette.

**Comment by r3volution11** [comment]
Excuse me if this isn't relevant but I have noticed a steep performance issue with my projects when the files are based in a Windows (10) VM. Windows software protection seems to go nuts when ColorHelper is enabled and immediately stops when I disable it.

**Comment by facelessuser** [comment]
This is not at all applicable to this issue.  There is no project scan at this point, so it can not possibly be affecting your VM.  Now whether ColorHelper, in general, puts a strain on the limited resources of your VM or not is a wholly separate issue.  If you would like to record this issue for possible work in the future, please file a separate issue following the template.

I would like to improve performance of ColorHelper in the future, but these things happen a little at a time.

**Comment by facelessuser** [comment]
I've decided I'm probably not going this route.

@gir-bot add S: wontfix
