### ISSUE TITLE
Settings not to change format

### ISSUE THREAD

**Issue by emkei-cz** [facelessuser/ColorHelper#82]
Hi,

It can be set to not change the format?

"#FFFFFF" > "#FFFFFF" = YES
"#FFFFFF" > "#FFF" = NO

<a href='https://postimg.org/image/i9ha8nlcn/' target='_blank'><img src='https://s23.postimg.org/i9ha8nlcn/image.png' border='0' alt='postimage'/></a>

<a href='https://postimg.org/image/a5963wyxj/' target='_blank'><img src='https://s23.postimg.org/a5963wyxj/image.png' border='0' alt='postimage'/></a>

Environment:
    ST ver.: 3126
    Platform: windows
    Arch: x64
    Plugin ver.: 2.4.1
    Install via PC: True
    mdpopups ver.: 1.13.1
    markdown ver.: 2.6.6
    pygments ver.: 2.1a0
    jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Compress hex output controls this: https://github.com/facelessuser/ColorHelper/blob/master/color_helper.sublime-settings#L96.

**Comment by emkei-cz** [comment]
NICE THX!
