### ISSUE TITLE
Palettes with "&" in name cannot be added to, opened, or deleted

### ISSUE THREAD

**Issue by beachmg** [facelessuser/ColorHelper#84]
## Description

If a palette is created with an "&" (AMPERSAND, U+0026) anywhere in the name, it stores correctly and shows up in the palette list but it cannot be opened, added to, or deleted.  The only way to get rid of it is to manually remove it from `Packages/User/color_helper.palettes`

no console errors occur at any point

## Support Info

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.4.1
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1. Open the Color Info Panel and select Add at the top
2. Click on Create New Palette
3. For the Palette Name enter anything as long as it includes the ampersand symbol (&)
4. Re-open the Color Info Panel and select Add
5. Scroll to the Palette you just created and if you click on it you'll see that nothing happens.
6. Open the Palette Panel and select Delete at the top
7. Select the Palette you created  and you'll see that again, nothing happens.
8. To delete your test palette you'll need to navigate to Packages/User/color_helper.palettes and delete the entry for the palette in that file.

I've tried to duplicate this behaviour with other symbols and they all work fine as far as I can tell. But as you can see in this picture, anything with an "&" has these issues:

![capture3](https://cloud.githubusercontent.com/assets/8540477/22527208/48f60e68-e89c-11e6-867d-beea3611b387.gif)

**Comment by facelessuser** [comment]
That's the fanciest annotation of an image I've seen yet :smile:.

Anyways, yeah, that looks like a problem.  I'm sure its more than `&` that can do that as well.  Hmm.  Well I've got some ideas.  When I have a chance I'll take a look.

**Comment by facelessuser** [comment]
It's a HTML escape issue.  I'll have it resolved in the next version.
