### ISSUE TITLE
How to make it work inside js file with quoted strings?

### ISSUE THREAD

**Issue by coodoo** [facelessuser/ColorHelper#87]
I'm mostly working with `react` and `jsx`, wondering is it possible to make the color helper work within js files, for code like below, it would be nice to have a color preview in `activeTintColor` property.

```javascript
tabBarOptions: {
	showIcon: false,
	activeTintColor: '#ff0000',
	labelStyle: {
		fontSize: 24,
		color: '#ff0000',
	},
},
```

**Comment by facelessuser** [comment]
Sorry I haven't gotten to this issue until now.  This can be added,  but you will have to familiarize yourself with the scopes in your `react` and `jsx` syntaxes.  I'd read the ColorHelper documentation and look at the settings file and see how rules are defined for CSS, HTML, etc.  By reading the documentation and using the current settings as a guide, you should be able to leverage those examples to so the same for `react` and `jsx`.  If you have specific questions, please to do ask.
