### ISSUE TITLE
Incorrect color indicator in distraction mode

### ISSUE THREAD

**Issue by scarigor** [facelessuser/ColorHelper#90]
When distraction mode is enabled with   "draw_centered": true,  color indicator is placed in wrong place.
![image](https://cloud.githubusercontent.com/assets/15365823/24266016/11576058-100e-11e7-9f14-fe91f34975c2.png)

**Comment by facelessuser** [comment]
1. I believe this issue should be taken up with the Sublime Text team as this is an issue with their phantom implementation.  It does not render them at the perceived text position the text is at. 
2. Please follow the [template](https://github.com/facelessuser/ColorHelper/blob/master/.github/ISSUE_TEMPLATE.md) for any further discussion.  Version number reports and reproducible steps make my life much easier when dealing with issues. It is something I ask all issue submitters to provide.
