### ISSUE TITLE
HTML special characters are also recognised as colors

### ISSUE THREAD

**Issue by bram-ontoforce** [facelessuser/ColorHelper#91]
When using HTML special characters in html element attributes, they are also recognised as colors.

- ST ver.: 3126
- Platform: osx
- Arch: x64
- Plugin ver.: 2.4.2
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

<img width="301" alt="screen shot 2017-04-14 at 11 33 59" src="https://cloud.githubusercontent.com/assets/16895543/25039857/4798306c-2106-11e7-9328-1710037bb827.png">

**Comment by facelessuser** [comment]
Yes, this does look problematic.
