### ISSUE TITLE
Flickers when mixing short and long color-codes

### ISSUE THREAD

**Issue by rwese** [facelessuser/ColorHelper#94]
## Description

When you have a CSS line with mixed short/long colors it will flicker.

### Console
no output

## Support Info
- ST ver.: 3143
- Platform: windows
- Arch: x64
- Plugin ver.: 2.5.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue
1. create css file with the following content:
```css
.SmallButton:active {
    border-color: #CCC #CCC #D9D9D9;
}
```
1. put cursor on the next to the ``{``
1. should flicker

![grafik](https://user-images.githubusercontent.com/7153716/30950635-76552b3a-a41e-11e7-8be5-45fdca011437.png)

**Comment by rwese** [comment]
Added a Bounty.  https://www.bountysource.com/issues/49820403-flickers-when-mixing-short-and-long-color-codes

**Comment by facelessuser** [comment]
This is actually an issue that crept in at some time.  We keep checking if we need to update colors when the scroll window changes.  Also, when the view buffer is modified we also clear the colors.  Unfortunately, the clear was happening every time the view buffer was modified **and** when we just check the scroll window (regardless of whether colors are updated or not).

This will be fixed in the next version.

**Comment by facelessuser** [comment]
Fix is in the new release: https://github.com/facelessuser/ColorHelper/releases/tag/st3-2.5.1.

**Comment by facelessuser** [comment]
Actually I'll leave this open until you confirm it's fixed mainly because a bounty is attached.

**Comment by rwese** [comment]
Thanks, with 2.5.1 the flickering is gone! So this can be closed and the bounty paid.

**Comment by facelessuser** [comment]
Thanks, I'll wait for you to approve it on bountysource so it can be claimed.

**Comment by rwese** [comment]
@facelessuser i believe you must post a claim for the bounty on bountysource so it can be approved. I haven't used bounties before, so I hope this isn't too confusing.

**Comment by facelessuser** [comment]
@rwese I've actually never used bounty source before either.  I am unable to claim until the backers have approved it appears.  I found this guide that explains it: http://mrbluecoat.blogspot.com/2017/03/bountysource-payment-process-backer.html.

**Comment by rwese** [comment]
Ok, i believe it wasn't the best idea to to thru bountysource, I am a little sorry... 
from that i gather you must post a claim still, I gave it the required vote but still says you are working on it
![grafik](https://user-images.githubusercontent.com/7153716/31340305-05c7c9d6-ad06-11e7-8af3-8fa8bbf5606b.png)

**Comment by facelessuser** [comment]
Cool maybe it just needs time. I'm new to it as well. I'll see if I need to do something on my end.

**Comment by facelessuser** [comment]
Well I can't figure out what else to do. Tried putting status in stopped and in progress. Their site is very unintuitive. If it works out great, if not I appreciate the gesture regardless :).

**Comment by facelessuser** [comment]
Looks like there is a lag.  But it finally allowed me to file a claim.
