### ISSUE TITLE
Using the color helper UI in Color Highlighter

### ISSUE THREAD

**Issue by Monnoroch** [facelessuser/ColorHelper#95]
Hi Isaac, I'm the main mainteiner of the Color Highlighter plugin and I'm in the process of releasing a completely new version, rewritten from scratch. Sublime Text gained a few new features over the years so I decided to use them in the remake. I included tools for highlighting colors using phantoms in it. However, I most certainly didn't go that far and didn't build an HTML based color picker.

Your UI is awesome and I wanted to ask for your permision to use it in my plugin (with appropriate credits). Your code is under MIT, so I know that technically I can use it freely, but I would still like to ask if you don't mind.

Thanks for the amazing work!

**Comment by facelessuser** [comment]
I guess I'm trying to get a feel for what you mean.  When you say use the UI, what do you mean?  I'm not sure what the end goal is.  Are you looking to essentially absorb ColorHelper into Color Highlighter?

**Comment by Monnoroch** [comment]
Not quite absorb. You have your own system for finding colors in text, for example. I'm pretty sure I don't want to integrate that part. I'm mostly interested in the UI widget for picking colors, favourite colors and all that good stuff. All the infrastructure for finding, parsing and canonicalizing colors is already implmented in Color Highlighter.

**Comment by facelessuser** [comment]
Yeah, that is fine. Does Color Highlighter still modify color schemes? That is the one thing that always kept me from using it.

**Comment by Monnoroch** [comment]
Yes, one of the features works like that, but only one of them just because it's the only way to do what's required. There are also othe ways to highlight colors: with gutter icons and phantoms (which is new). These do not modify color schemes. So it's just the matter of configuring the plugin.

**Comment by facelessuser** [comment]
Nice. If that's true, and it works really good, maybe I can retire mine. I'm not a web developer, i do firmware, so I don't use this plugin that much. It's one of the reasons it doesn't get as much love as some of my more used ones. So if basically yours is trying to take the #1 color spot, and it is better and better maintained, I'd gladly step aside.

Mine was always just a playground that turned into something that people really liked, which I wasn't prepared for. I maintain too much as is. So if yours has better color support, and takes the best of what this has...

**Comment by Monnoroch** [comment]
Mine was a playground for a few years too :) On the other hand, yours has amazing docs. Would be amazing if you could contribute to Color Highlighter and help me with all that stuff. You seem to be really good with github stuff and I do most of my development in private gitlab.

**Comment by facelessuser** [comment]
Docs is the easy part. I use [Mkdocs](https://github.com/mkdocs/mkdocs) (which uses Python Markdown), my own set of custom Python Markdown extensions [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions), and the [Material](https://github.com/squidfunk/mkdocs-material) theme.

Then I set it up to auto-deploy my docs with Travis when I release a tag .  Keeps it nice and easy 😄 .

I'd gladly help you set that up on yours. I'm a big fan of Mkdocs.  It's made document sites easy for me, which in turn made me make an effort to make decent documents.

**Comment by Monnoroch** [comment]
Awesome, thanks! Can't wait for your PRs :)
